### ISSUE TITLE
py2app fails with recent version of pyQt

### ISSUE THREAD

**Issue by chrmoritz** [wizzomafizzo/starcheat#111]
Pillow in more recent versions seems to cause issues with py2app

```
Traceback (most recent call last):
File "setup.py", line 11, in <module>
setup_requires=['py2app'],
File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 148, in setup
dist.run_commands()
File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
self.run_command(cmd)
File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
cmd_obj.run()
File "/usr/local/lib/python3.4/site-packages/py2app/build_app.py", line 659, in run
self._run()
File "/usr/local/lib/python3.4/site-packages/py2app/build_app.py", line 865, in _run
self.run_normal()
File "/usr/local/lib/python3.4/site-packages/py2app/build_app.py", line 959, in run_normal
self.create_binaries(py_files, pkgdirs, extensions, loader_files)
File "/usr/local/lib/python3.4/site-packages/py2app/build_app.py", line 1214, in create_binaries
platfiles = mm.run()
File "/usr/local/lib/python3.4/site-packages/macholib/MachOStandalone.py", line 105, in run
mm.run_file(fn)
File "/usr/local/lib/python3.4/site-packages/macholib/MachOGraph.py", line 84, in run_file
self.scan_node(m)
File "/usr/local/lib/python3.4/site-packages/macholib/MachOGraph.py", line 110, in scan_node
m = self.load_file(filename, caller=node)
File "/usr/local/lib/python3.4/site-packages/macholib/MachOGraph.py", line 93, in load_file
newname = self.locate(name, loader=caller)
File "/usr/local/lib/python3.4/site-packages/macholib/MachOStandalone.py", line 23, in locate
newname = super(FilteredMachOGraph, self).locate(filename, loader)
File "/usr/local/lib/python3.4/site-packages/macholib/MachOGraph.py", line 49, in locate
loader=loader.filename)
TypeError: dyld_find() got an unexpected keyword argument 'loader'
```

**Comment by DeltaLikeM** [comment]
I downgraded to Pillow 2.4 but its still crashing any resolution

**Comment by chrmoritz** [comment]
Continue downgrading other dependencies. The only thing I know so far is, that the current cached binaries on your build bot (as of 20 Apr 2014) are working, but I didn't have time to figure out what exactly is causing the issue. Working set:
* Python 3.4.0
* Qt 5.2.1
* PyQt 5.2.1
* Pillow 2.4.0
* Py2App 0.8
* modulegraph 0.11.1
* altgraph 0.11
* macholib 1.6

**Comment by chrmoritz** [comment]
This is definitely an issue with recent versions of py2app and Pillow.

**Comment by chrmoritz** [comment]
Issue is unrelated to the version of:
* python, pip, setup tools, easyinstall

**Comment by chrmoritz** [comment]
Here is a working build with up to date python3 and Pillow, py2app and deps:
https://github.com/chrmoritz/starcheat/releases/tag/9.9.4
