### ISSUE TITLE
Stable Crash

### ISSUE THREAD

**Issue by kurisubrooks** [wizzomafizzo/starcheat#119]
It just finished indexing the assets, then crashed.

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/PIL/Image.py", line 395, in _getdecoder
    decoder = getattr(core, decoder_name + "_decoder")
AttributeError: 'module' object has no attribute 'zip_decoder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/starcheat", line 74, in <module>
    main()
  File "/usr/local/bin/starcheat", line 71, in main
    gui.mainwindow.MainWindow()
  File "/usr/local/Cellar/starcheat/HEAD/libexec/gui/mainwindow.py", line 134, in __init__
    open_player = self.open_file()
  File "/usr/local/Cellar/starcheat/HEAD/libexec/gui/mainwindow.py", line 417, in open_file
    character_select = CharacterSelectDialog(self.window, self.assets)
  File "/usr/local/Cellar/starcheat/HEAD/libexec/gui/utils.py", line 332, in __init__
    self.populate()
  File "/usr/local/Cellar/starcheat/HEAD/libexec/gui/utils.py", line 375, in populate
    preview = self.assets.species().render_player(player)
  File "/usr/local/Cellar/starcheat/HEAD/libexec/assets.py", line 1111, in render_player
    player.get_body_directives())
  File "/usr/local/Cellar/starcheat/HEAD/libexec/assets.py", line 1098, in grab_sprite
    img = Image.open(BytesIO(sheet)).convert("RGBA").crop(rect)
  File "/usr/local/lib/python3.4/site-packages/PIL/Image.py", line 729, in convert
    self.load()
  File "/usr/local/lib/python3.4/site-packages/PIL/ImageFile.py", line 191, in load
    d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
  File "/usr/local/lib/python3.4/site-packages/PIL/Image.py", line 399, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
OSError: decoder zip not available

**Comment by wizzomafizzo** [comment]
don't think i've seen this one before!

do you have any species mods installed and used or is this just vanilla?

**Comment by kurisubrooks** [comment]
Vanilla, with some client mods.

**Comment by wizzomafizzo** [comment]
what are client mods?

from the looks of it it's happening when it tries to load the list of all player files and try render the icons. is it correct that it happens after it says "index X number of assets" dialog but before the player list showed up at all?

if so, when you have time, could you please try track down which specific player file is causing it? i will do some testing though too see if i can reproduce

**Comment by kurisubrooks** [comment]
I only have 1 player file, and the mods I have installed are:

- Extended Songbook
- Planetside Respawn
- More Zoom Options

**Comment by wizzomafizzo** [comment]
oh ok that makes things easier. one last thing then, can you please upload the player somewhere and i'll give it a shot

**Comment by kurisubrooks** [comment]
Hold on a bit, I think I just corrupted it ;)

**Comment by kurisubrooks** [comment]
Just tried again, now getting this error:

Traceback (most recent call last):
  File "/usr/local/bin/starcheat", line 74, in <module>
    main()
  File "/usr/local/bin/starcheat", line 71, in main
    gui.mainwindow.MainWindow()
  File "/usr/local/Cellar/starcheat/HEAD/libexec/gui/mainwindow.py", line 98, in __init__
    for species in self.assets.species().get_species_list():
  File "/usr/local/Cellar/starcheat/HEAD/libexec/assets.py", line 350, in species
    return Species(self)
  File "/usr/local/Cellar/starcheat/HEAD/libexec/assets.py", line 931, in __init__
    self.assets.vanilla_assets)
  File "/usr/local/Cellar/starcheat/HEAD/libexec/assets.py", line 306, in read
    db = starbound.open_file(path)
  File "/usr/local/Cellar/starcheat/HEAD/libexec/starbound/helpers.py", line 212, in open
    return read_stream(builtins.open(path, 'rb'), extension)
  File "/usr/local/Cellar/starcheat/HEAD/libexec/starbound/helpers.py", line 219, in read_stream
    file.initialize()
  File "/usr/local/Cellar/starcheat/HEAD/libexec/starbound/btreedb4.py", line 119, in initialize
    super(FileBTreeDB4, self).initialize()
  File "/usr/local/Cellar/starcheat/HEAD/libexec/starbound/sbbf02.py", line 89, in initialize
    assert stream.read(6) == b'SBBF02', 'Invalid file format'
AssertionError: Invalid file format

**Comment by kurisubrooks** [comment]
I'm gonna try to fresh reinstall again.

**Comment by kurisubrooks** [comment]
https://dl.dropboxusercontent.com/u/88968327/820833c1d824894f5bba04ea92f93768.player

**Comment by kurisubrooks** [comment]
I'm not getting the error anymore, after the fresh install :(

**Comment by chrmoritz** [comment]
The `assert stream.read(6) == b'SBBF02', 'Invalid file format'` issues was related to not updating the submodule and using the old unstable/nightly save format.
