### ISSUE TITLE
Crash - Glass Coffee Mug

### ISSUE THREAD

**Issue by kurisubrooks** [wizzomafizzo/starcheat#120]
Crashed when I clicked on the Glass Coffee Mug in the Item Explorer

Traceback (most recent call last):
  File "gui/itembrowser.pyc", line 140, in update_item_view
  File "assets.pyc", line 583, in get_item
  File "assets.pyc", line 331, in read
  File "assets.pyc", line 49, in load_asset_file
NotADirectoryError: [Errno 20] Not a directory: '/Users/Kurisu/Library/Application Support/Steam/SteamApps/common/Starbound/assets/packed.pak/items/generic/crafting/glasscoffeemug.item'

**Comment by wizzomafizzo** [comment]
@kurisubrooks is this still not working for you? i was not able to reproduce it since the latest version

**Comment by kurisubrooks** [comment]
Seems to be fixed!
