### ISSUE TITLE
Crash after character selection

### ISSUE THREAD

**Issue by ThrowawayHooray** [wizzomafizzo/starcheat#125]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 134, in __init__
  File "build\gui\mainwindow.py", line 426, in open_file
  File "build\gui\mainwindow.py", line 195, in update
  File "build\gui\mainwindow.py", line 554, in update_bag
KeyError: '__content'

Not sure what to do

**Comment by wizzomafizzo** [comment]
are you able to upload the player file this is erroring on? it seems like there's a corrupt item in there tripping it up but not 100% sure

**Comment by wizzomafizzo** [comment]
Can you please let us know if this is fixed with the latest 0.19 version of starcheat. Thanks

**Comment by wizzomafizzo** [comment]
going to close this now, i believe we've had reports by other people that this is fixed anyway. please comment if it's not fixed and you'd like to reopen the ticket
