### ISSUE TITLE
Crash selecting commonbroadsword

### ISSUE THREAD

**Issue by Flipdecoin** [wizzomafizzo/starcheat#133]
Traceback (most recent call last):
  File "build\gui\itemedit.py", line 377, in set_item_browser_selection
  File "build\gui\itemedit.py", line 266, in update_item
  File "build\gui\itemedit.py", line 252, in <lambda>
  File "build\assets.py", line 815, in generate_sword
KeyError: 'projectileTypes'

**Comment by wizzomafizzo** [comment]
good catch btw! should be easy to add an exception for this. do you know if the working swords are still generating valid items?

**Comment by wizzomafizzo** [comment]
should be working in dev branch now. please test now if you can, otherwise wait for next release and let us know

**Comment by chrmoritz** [comment]
@Flipdecoin: This should be fixed now. Please report back and reopen this issue if your problems persist in [starcheat 0.20](https://github.com/wizzomafizzo/starcheat/releases/tag/0.20).
