### ISSUE TITLE
StarCheat Does not like Race mods

### ISSUE THREAD

**Issue by WinterSpecter** [wizzomafizzo/starcheat#135]
Ok so I already know what caused it and can go around it decently easily. So I am just reporting this. I found that when I had a player file that was a race from a race mod starcheat would crash the instant I tried to launch it. here is the crash log.

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 134, in __init__
  File "build\gui\mainwindow.py", line 417, in open_file
  File "build\gui\utils.py", line 332, in __init__
  File "build\gui\utils.py", line 375, in populate
  File "build\assets.py", line 1093, in render_player
TypeError: 'NoneType' object is not subscriptable

**Comment by chrmoritz** [comment]
We had a bug looking for mods in the old location and not in `giraffe_storage`which is fixed in dbf1682. (Refs #136) Could you please try, if this has fixed your issue.

**Comment by chrmoritz** [comment]
Binaries for this are now up at https://github.com/chrmoritz/starcheat/releases/tag/0.18.2 for testing.

**Comment by WinterSpecter** [comment]
Ty this update has indeed fixed the problem keep up the good work!
