### ISSUE TITLE
Crash on run

### ISSUE THREAD

**Issue by KimikoMuffin** [wizzomafizzo/starcheat#137]
I was working a bit on a weapons-mod and checking various things with version 1.8.2 of StarCheat. I added some custom projectiles, and suddenly got the following crash every time StarCheat tries to load the main window, even after I removed the custom projectiles:

    Traceback (most recent call last):
      File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
      File "build\starcheat.py", line 74, in <module>
      File "build\starcheat.py", line 71, in main
      File "build\gui\mainwindow.py", line 67, in __init__
      File "build\gui\utils.py", line 95, in check_index_valid
      File "build\gui\utils.py", line 66, in build_assets_db
      File "build\assets.py", line 194, in create_index
      File "build\assets.py", line 543, in index_data
    TypeError: list indices must be integers, not str

**Comment by chrmoritz** [comment]
You should be able to fix the crash if you [reset your settings](https://github.com/wizzomafizzo/starcheat/wiki/help#reset-all-settings) and force starcheat to reindex the asserts without the mod.
For the error: it tries to read a Dictionary/map with itemName, name, and objectName as keys but is only able to read a list/array. Providing a minimalistic as possible test mod, which causes the error would be helpful.

**Comment by KimikoMuffin** [comment]
Ah, here we go: it was being caused by a different mod than the one I thought it was. The culprit mod consisted entirely of "[existing asset].patch" files, each with a single "op":"replace" command. As in, "[moddir]/items/tools/miningtools/copperdrill.miningtool.patch":

    [ { "op" : "replace", "path" : "/durabilityPerUse", "value" : 2 } ]

**Comment by wizzomafizzo** [comment]
that's weird i thought the patch files were filtered out, will have to double check. thanks for the report!

**Comment by Kataclysm69** [comment]
I have this Issue
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 134, in __init__
  File "build\gui\mainwindow.py", line 417, in open_file
  File "build\gui\utils.py", line 332, in __init__
  File "build\gui\utils.py", line 375, in populate
  File "build\assets.py", line 1093, in render_player
TypeError: 'NoneType' object is not subscriptable

**Comment by chrmoritz** [comment]
This is the same issue as in #138, you can try a preview build from here with a fix: https://github.com/chrmoritz/starcheat/releases/tag/0.18.2

**Comment by wizzomafizzo** [comment]
hi @KimikoMuffin could you let us know if this is fixed now? i'm pretty sure i found what the problem was in that patch

**Comment by KimikoMuffin** [comment]
Yep, it's working fine on my end.
