### ISSUE TITLE
Crash on Start

### ISSUE THREAD

**Issue by Vexrak** [wizzomafizzo/starcheat#138]
Code:

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 134, in __init__
  File "build\gui\mainwindow.py", line 417, in open_file
  File "build\gui\utils.py", line 332, in __init__
  File "build\gui\utils.py", line 375, in populate
  File "build\assets.py", line 1093, in render_player
TypeError: 'NoneType' object is not subscriptable

**Comment by wizzomafizzo** [comment]
hi, can you please try out this version and see if it fixes what's going on if you haven't already: https://github.com/chrmoritz/starcheat/releases/tag/0.18.2

make sure the starcheat config folder has been cleared out too

if that doesn't help at all could you please upload your player file somewhere and i will get a patch in pretty soon

**Comment by Vexrak** [comment]
Thanks, I think when I downloaded it I accidentally stopped the indexing. Anyways thanks and keep up the great work on StarCheat

**Comment by chrmoritz** [comment]
Glad to hear that it is working for you now.
BTW: This issues was related to indexing old mods in the old mod location.

**Comment by Vexrak** [comment]
Oh thanks :)

**Comment by Paulingen** [comment]
Looks like this don't work in my pc i downloaded the version 0.18; 0.18.1 and 0.18.2 but still don't work, can anyone tell me what is wrong with my pc or SC?
