### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Trollzy** [wizzomafizzo/starcheat#140]
---------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 134, in __init__
  File "build\gui\mainwindow.py", line 426, in open_file
  File "build\gui\mainwindow.py", line 195, in update
  File "build\gui\mainwindow.py", line 554, in update_bag
KeyError: '__content'
-----------------------------------------------------------------------------------------------------------------------------

I open my character and it crashes.

**Comment by Kataclysm69** [comment]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 134, in __init__
  File "build\gui\mainwindow.py", line 417, in open_file
  File "build\gui\utils.py", line 332, in __init__
  File "build\gui\utils.py", line 375, in populate
  File "build\assets.py", line 1093, in render_player
TypeError: 'NoneType' object is not subscriptable

**Comment by chrmoritz** [comment]
#125

**Comment by wizzomafizzo** [comment]
Can you please let us know if the latest version of starcheat fixes this issue. Thanks.

**Comment by chrmoritz** [comment]
Closing this in favor of #125
