### ISSUE TITLE
Crashes upon viewing item browser

### ISSUE THREAD

**Issue by PwnerPro** [wizzomafizzo/starcheat#145]
Here is the crash report. Traceback (most recent call last):
  File "build\gui\mainwindow.py", line 359, in new_item_browser
  File "build\gui\itembrowser.py", line 101, in __init__
  File "build\config.py", line 32, in read
  File "C:\Python34\lib\configparser.py", line 937, in __getitem__
KeyError: 'starcheat'
Hope this helped you guys over at starcheat at fixing all the bugs!

**Comment by chrmoritz** [comment]
Please [reset all settings](https://github.com/wizzomafizzo/starcheat/wiki/help#reset-all-settings). The 0.8.0 release has missed to bump the config version.

**Comment by wizzomafizzo** [comment]
closing this now, seems pretty certain this got fixed when the config version was bumped. please comment if you want to reopen the ticket
