### ISSUE TITLE
Crash on viewing tech, in game and starcheat

### ISSUE THREAD

**Issue by Kelazun** [wizzomafizzo/starcheat#146]
Traceback (most recent call last):
  File "build\gui\techs.py", line 64, in __init__
  File "build\assets.py", line 1330, in get_tech
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build\gui\mainwindow.py", line 387, in new_techs_dialog
  File "build\gui\techs.py", line 71, in __init__
KeyError: 'modulePath'

**Comment by Kelazun** [comment]
Only happens on the specific character when selecting him.

**Comment by wizzomafizzo** [comment]
this will be fixed in the next release which should be happening later today. not to worry if you want to keep the character too, the errors will be recoverable in the new version

**Comment by chrmoritz** [comment]
Could you please try [version 0.19](https://github.com/wizzomafizzo/starcheat/releases/tag/0.19) and report back if this has fixed your issue.
