### ISSUE TITLE
Trouble getting 0.19 to run.

### ISSUE THREAD

**Issue by lordcarlton** [wizzomafizzo/starcheat#154]
Every time I start the program, I am met with:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 134, in __init__
  File "build\gui\mainwindow.py", line 417, in open_file
  File "build\gui\utils.py", line 330, in __init__
  File "build\gui\utils.py", line 364, in populate
  File "build\assets.py", line 1094, in render_player
TypeError: 'NoneType' object is not subscriptable

I have no mods installed, but I'm not sure what is causing this. If anyone could help out, I would appreciate it.

**Comment by wizzomafizzo** [comment]
hi. just want to rule out a starcheat upgrade issue, can you make sure the settings are all cleared out and try again? https://github.com/wizzomafizzo/starcheat/wiki/help#reset-all-settings

if you already did that, could you upload a copy of your player file(s) and we can look into it

**Comment by lordcarlton** [comment]
Deleting the Assets only gave me a different error message: 

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 98, in __init__
  File "build\assets.py", line 956, in get_species_list
sqlite3.OperationalError: no such table: assets

If it is okay with you, it would be most convenient to email you a .rar of my files. Would you mind that?

**Comment by wizzomafizzo** [comment]
if you like. email is on my main profile page

by the looks of this error is seems like the database was deleted but the ini file still exists. could you try remove the entire starcheat folder in your appdata

**Comment by Lyynus** [comment]
Traceback (most recent call last):
File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in 
File "build\starcheat.py", line 74, in 
File "build\starcheat.py", line 71, in main
File "build\gui\mainwindow.py", line 134, in init
File "build\gui\mainwindow.py", line 417, in open_file
File "build\gui\utils.py", line 330, in init
File "build\gui\utils.py", line 364, in populate
File "build\assets.py", line 1094, in render_player
TypeError: 'NoneType' object is not subscriptable

Here's the error again. Has this happened to more people and can it be resolved easily? I'll just upload an updated version with both my characters and their player files with updated logs.

https://www.dropbox.com/sh/p9ybdeuchj4p7i9/AACwvupMTobrbCQxbO_riPo7a?dl=0

**Comment by wizzomafizzo** [comment]
i'm not sure how easy it will be to fix, still need to investigate. this is one of the issues on my radar for next release though

the errors to me look like a bad assets index though, i think the only fix i'll be able to provide is to skip over the rendered player and use a placeholder image instead, there will still be the greater issue of why it's doing this in the first place

who knows though, i will update when i have more information

**Comment by wizzomafizzo** [comment]
@Lyynus i stall can't reproduce it. could i get you to upload your starcheat logs as well?

https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs

**Comment by wizzomafizzo** [comment]
@lordcarlton can you please confirm is this is fixed for you in the latest 0.20 release? it should have at least stopped crashing

**Comment by lordcarlton** [comment]
Sorry for my inactivity, I've been away for a while. And, as of 0.20, Starcheat seems to work well as well as being compatible with all of my active mods.

**Comment by wizzomafizzo** [comment]
excellent, and not a problem at all man. thanks for your report, always happy to get feedback!

**Comment by lordcarlton** [comment]
Thanks for the help, though. I appreciate it!
