### ISSUE TITLE
[SBBF] Starcheat crashing when it opens.

### ISSUE THREAD

**Issue by DrVivid** [wizzomafizzo/starcheat#155]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 67, in __init__
  File "build\gui\utils.py", line 95, in check_index_valid
  File "build\gui\utils.py", line 57, in build_assets_db
  File "build\assets.py", line 228, in find_assets
  File "build\assets.py", line 234, in scan_modpak
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

**Comment by chrmoritz** [comment]
Try to remove the not yet for upbeat giraffe updated mod from your mod folder.

**Comment by DrVivid** [comment]
I don't have any mods that aren't updated.

**Comment by chrmoritz** [comment]
You have, something is using the olds file format.

**Comment by SolidScout** [comment]
I'm having this same issue, with the same log as DrVivid, the two mods I have installled are both up to date with upbeat giraffe and work perfectly in game, I'm not entirely sure what the problem could be, but some help would be appreciated.

**Comment by chrmoritz** [comment]
At the moment starcheat requires mods updated for upbeat giraffe, but starbound itself is compatible with some older unstable mods.

**Comment by SolidScout** [comment]
Both mods I have (MMX and weapons of star wars) have been updated for upbeat giraffe, is there a way I can check if they really have been?

**Comment by chrmoritz** [comment]
Run starcheat, if you see a `AssertionError: Invalid file format` error then they are using the old pack format. But we will handle both formats mist likely in the next version.

**Comment by SolidScout** [comment]
Is there a way to repack the modpaks to the new format (if possible)?

**Comment by chrmoritz** [comment]
use upbeat giraffe starbound to pack them

**Comment by Lyynus** [comment]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 134, in __init__
  File "build\gui\mainwindow.py", line 417, in open_file
  File "build\gui\utils.py", line 330, in __init__
  File "build\gui\utils.py", line 364, in populate
  File "build\assets.py", line 1094, in render_player
TypeError: 'NoneType' object is not subscriptable

Earlier today I was using starcheat just find until just a few minutes ago this error occured. I thought it was just some random mistake and disregarded it and tried opening it again and again a few times over, but it kept appearing. Not sure what it is, but thought I should post it.

**Comment by wizzomafizzo** [comment]
@Lyynus that error will be unrelated to this ticket but could you please upload another copy of your characters. i have been trying to reproduce this error for a while now

perhaps post it in that ticket we were figuring out the other stuff in

**Comment by chrmoritz** [comment]
Everyone having issues with mods in the old sbbf02 format should try out [version 0.19.1](https://github.com/wizzomafizzo/starcheat/releases/tag/0.19.1) which should fix your issues.

**Comment by chrmoritz** [comment]
The SBBF should be fixed and the other issues is handled in it's own issue. Closing this now.

**Comment by Carnage2089** [comment]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 558, in open_file
  File "build\gui\mainwindow.py", line 222, in update
  File "build\gui\mainwindow.py", line 830, in update_stat
  File "build\saves.py", line 544, in get_health
KeyError: 'resourceValues'

What does this mean?
