### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Blademuise** [wizzomafizzo/starcheat#160]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 136, in __init__
  File "build\gui\mainwindow.py", line 418, in open_file
  File "build\gui\utils.py", line 352, in __init__
  File "build\gui\utils.py", line 386, in populate
  File "build\assets.py", line 1097, in render_player
TypeError: 'NoneType' object is not subscriptable

**Comment by wizzomafizzo** [comment]
hi. this error will have a workaround put in place in the next release (very soon) which will let you get into starcheat without a crash. the problem is this does not fix the underlying issue of starcheat not recognising your species, it will just replace the preview image with an X

see how you go when the next release is out, but could you please also pastebin a copy of your starcheat log: https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs

**Comment by Blademuise** [comment]
Ah. The release came out and it is working fine now. Thanks!
