### ISSUE TITLE
cannot load NaN float stats

### ISSUE THREAD

**Issue by FanatiG** [wizzomafizzo/starcheat#166]
restarted computer and now i have:

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 140, in __init__
  File "build\gui\mainwindow.py", line 452, in open_file
  File "build\gui\mainwindow.py", line 180, in update
  File "build\gui\mainwindow.py", line 672, in update_stat
ValueError: cannot convert float NaN to integer

p.s.
(i tried to download new starcheat archive, but have the same problem)

**Comment by FanatiG** [comment]
i made backup with the help of second player, now it is ok :D

**Comment by wizzomafizzo** [comment]
do you still have a copy of it? haven't seen this before but should be fixable. did you have an item equipped that gave super high stats or anything like that?

thanks for these reports btw they're very interesting

**Comment by wizzomafizzo** [comment]
should be fixed in next release

NaN translates to dead for starbound. gonna default to full instead, doesn't really matter if it's accurate since it's just the current values

**Comment by chrmoritz** [comment]
This should be fixed now in [starcheat 0.21](https://github.com/wizzomafizzo/starcheat/releases/tag/0.21). Please tell us if you have still issues.
