### ISSUE TITLE
I have know idea, please assist

### ISSUE THREAD

**Issue by msagate18** [wizzomafizzo/starcheat#167]
sorry for gramer mistake, my English is poor
  
starting it up for the first time and got this:
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 164, in __init__
  File "build\gui\mainwindow.py", line 467, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 91, in get_players
  File "build\saves.py", line 457, in __init__
  File "build\saves.py", line 508, in import_save
  File "build\saves.py", line 384, in __init__
  File "build\saves.py", line 392, in import_metadata
  File "build\saves.py", line 302, in unpack_var
  File "build\saves.py", line 262, in unpack_starsave
  File "build\saves.py", line 221, in unpack_variant
TypeError: 'NoneType' object is not callable, it crashes the give

Please help or can you tell me whats wrong

**Comment by chrmoritz** [comment]
Thanks for reporting this, could you please [your starcheat log](https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs) and the affected player file.

**Comment by msagate18** [comment]
http://dpaste.com/3M6YDKP is this what you needed

**Comment by wizzomafizzo** [comment]
could you please upload a copy of your player save file too. you can upload to somewhere like mega.co.nz

**Comment by chrmoritz** [comment]
The affected player file should be `C:\Program Files (x86)\Steam\SteamApps\common\Starbound\giraffe_storage\player\18cecda3cdb8b3ad02a5482f1a56b0c6.player`

**Comment by wizzomafizzo** [comment]
@msagate18 please let us know if this is still happening. Closing for now
