### ISSUE TITLE
Improper directives crash

### ISSUE THREAD

**Issue by IIWOLFII** [wizzomafizzo/starcheat#169]
I clicked on button "Make new option" and wrote in "directives", leaving null unchanged and got crash with following error log:

Traceback (most recent call last):
  File "build\gui\mainwindow.py", line 255, in <lambda>
  File "build\gui\mainwindow.py", line 708, in new_main_bag_item_edit
  File "build\gui\mainwindow.py", line 349, in new_item_edit
  File "build\gui\itemedit.py", line 181, in launch
  File "build\gui\itemedit.py", line 186, in update
  File "build\gui\itemedit.py", line 221, in update_item_info
  File "build\assets.py", line 461, in color_image
  File "build\assets.py", line 110, in unpack_color_directives
TypeError: expected string or buffer

I'm probably doing it wrong, but i don't see any other way to add directives to items

**Comment by IIWOLFII** [comment]
My bad, i forgot to add "" to lower field.

**Comment by wizzomafizzo** [comment]
hi there. thanks for your report and glad you worked out the issue! i'll make sure this gets fixed, even if you're putting the directives in wrong it should not be fatal

**Comment by wizzomafizzo** [comment]
Fixed in that commit. Please let me know if it's not working in the next release. Thanks!
