### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ProGamersRo** [wizzomafizzo/starcheat#170]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 67, in __init__
  File "build\gui\utils.py", line 95, in check_index_valid
  File "build\gui\utils.py", line 57, in build_assets_db
  File "build\assets.py", line 214, in find_assets
  File "build\assets.py", line 241, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

**Comment by chrmoritz** [comment]
what version of starcheat are you using? stable/unstable/a outdated one?

**Comment by wizzomafizzo** [comment]
please reply if this is still happening for you and i will reopen. closing
