### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TheControllerCat** [wizzomafizzo/starcheat#173]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 164, in __init__
  File "build\gui\mainwindow.py", line 467, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 101, in get_players
  File "build\gui\openplayer.py", line 113, in populate
  File "build\assets.py", line 1140, in render_player
  File "build\assets.py", line 1127, in grab_sprite
  File "C:\Python34-x64\lib\site-packages\PIL\Image.py", line 2274, in open
OSError: cannot identify image file <_io.BytesIO object at 0x0000000005FC66A8>

**Comment by TheControllerCat** [comment]
Removing my mods seems to have fixed the problem.

**Comment by wizzomafizzo** [comment]
Hi. What mod was it? We can add an exception
