### ISSUE TITLE
python crash

### ISSUE THREAD

**Issue by axotion** [wizzomafizzo/starcheat#187]
2015-05-03 13:36:15,176 INFO     starcheat init
2015-05-03 13:36:15,176 INFO     Version: 0.22 (Spirited Giraffe)
2015-05-03 13:36:15,177 INFO     Platform: Linux
2015-05-03 13:36:15,177 INFO     Checking for updates
2015-05-03 13:36:15,414 INFO     Main window init
2015-05-03 13:36:15,415 DEBUG    Traceback (most recent call last):

2015-05-03 13:36:15,415 DEBUG      File "/usr/share/starcheat/starcheat.py", line 74, in <module>
    main()

2015-05-03 13:36:15,415 DEBUG      File "/usr/share/starcheat/starcheat.py", line 71, in main
    gui.mainwindow.MainWindow()

2015-05-03 13:36:15,415 DEBUG      File "/usr/share/starcheat/gui/mainwindow.py", line 92, in __init__
    self.ui.actionSave.triggered.connect(self.save)

2015-05-03 13:36:15,415 DEBUG    AttributeError: 'Ui_MainWindow' object has no attribute 'actionSave'

My packages:
qt5-connectivity 5.4.1-4
qt5-declarative 5.4.1-4
qt5-enginio 5.4.1-4
qt5-graphicaleffects 5.4.1-4
qt5-imageformats 5.4.1-4
qt5-location 5.4.1-4
qt5-multimedia 5.4.1-4
qt5-quick1 5.4.1-4
qt5-quickcontrols 5.4.1-4
qt5-script 5.4.1-4
qt5-sensors 5.4.1-4
qt5-serialport 5.4.1-4
qt5-svg 5.4.1-4
qt5-tools 5.4.1-4
qt5-translations 5.4.1-4
qt5-wayland 5.4.1-4
qt5-webchannel 5.4.1-4
qt5-webengine 5.4.1-4
qt5-webkit 5.4.1-4
qt5-websockets 5.4.1-4
qt5-x11extras 5.4.1-4
qt5-xmlpatterns 5.4.1-4
wireshark-qt 1.12.4-3

Python version: python-3.4.3-2
Downloaded from AUR https://aur.archlinux.org/packages/starcheat/

**Comment by wizzomafizzo** [comment]
I'll have to test this when I've got my arch machine booted up. Does it still do it if you build from the latest git version instead?

**Comment by GabMus** [comment]
I have the same problem, both from the AUR package and by compiling the program from source.

**Comment by wizzomafizzo** [comment]
@GabMus could you please try running it with the latest git version and let me know how that goes as well

**Comment by GabMus** [comment]
@wizzomafizzo same exact error. I'm trying to debug it right now, it seems like none of the actions starting from line 92 of gui/mainwindow.py are found. These include 
self.ui.actionSave.triggered.connect(self.save) #bug cazzone
        self.ui.actionReload.triggered.connect(self.reload)
        self.ui.actionOpen.triggered.connect(self.open_file)
        self.ui.actionQuit.triggered.connect(self.app.closeAllWindows)
        self.ui.actionOptions.triggered.connect(self.new_options_dialog)
        self.ui.actionItemBrowser.triggered.connect(self.new_item_browser)
        self.ui.actionAbout.triggered.connect(self.new_about_dialog)
        self.ui.actionExport.triggered.connect(self.export_save)
        self.ui.actionExportJSON.triggered.connect(self.export_json)
        self.ui.actionImportJSON.triggered.connect(self.import_json)
        self.ui.actionMods.triggered.connect(self.new_mods_dialog)
        self.ui.actionImageBrowser.triggered.connect(self.new_image_browser_dialog)

**Comment by wizzomafizzo** [comment]
i still can't test this. i did check the packages and i think qt5 had been updated within the last month or so? do you know if it was working back then?

**Comment by GabMus** [comment]
I don't know sorry. You could just deploy an Antergos (Arch based, same
repos, easy install) VM if you need to test it.
