### ISSUE TITLE
Spirited Giraffe: Starcheat Crashes upon Opening

### ISSUE THREAD

**Issue by Marcfyre** [wizzomafizzo/starcheat#192]
Hello, hello!
Alright, so I was using the Upbeat Giraffe version of Starcheat today, and opened it up, intending to import a .json. Upon cracking it open, I found an update was available for Spirited Giraffe Starcheat. Naturally, I instantly went and downloaded it, deleting the old version.
However, upon opening it, whenever the program gets to 53% of reading player files, it dies with this log:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 548, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 93, in get_players
  File "build\assets\species.py", line 335, in render_player
  File "build\assets\species.py", line 224, in render_chest
TypeError: 'NoneType' object is not subscriptable

If anyone could help me so I can get back to modding in that sweet Teleporter .json that lets me go to hubs on my server...well, tha'd be just Spiffy.

~Marc

**Comment by Darkblader24** [comment]
I got the almost same error, but while loading my player files on start:

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 548, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 93, in get_players
  File "build\assets\species.py", line 339, in render_player
  File "build\assets\species.py", line 207, in render_part
  File "build\assets\images.py", line 27, in get_image
IndexError: list index out of range

**Comment by wizzomafizzo** [comment]
Must be some things that haven't been handled properly in the player preview rendering step. I'll try get a hotfix out for this soon. If possible, could I please get copies of the player files that this is happening to.

**Comment by wizzomafizzo** [comment]
ah ok i see where the issue it, it should be pretty easy to fix. when you can, please still send me a copy of your player files or at least a list of what armour your character has equipped. it's easy enough for me to ignore the errors and skip showing that armour piece but better if i can get a specific example and then code in support

**Comment by Darkblader24** [comment]
I do have two player files crashing Starcheat:
http://puu.sh/hZNvh.player
http://puu.sh/hZNEH.player

Btw, thanks for your support and this awesome program :)

**Comment by wizzomafizzo** [comment]
Thanks! And no worries :)

Btw it's some effort involved but starcheat should work fine if you unequip your armour in game before you start it (and don't equip any other armour that triggers it).

**Comment by IsaiahJM97** [comment]
I am pretty sure I have the same error as the others but I just wanted to post my error here as well to give some confimation or heads-up in the means of what is happening. The steps I have taken:

1). Open Starcheat w/o administrative help (W/o running as admin)

"Oops, Starcheat has crashed. To report this error,..."  <--- That error is upon opening Starcheat
I haven't even loaded my character yet.. I am not sure if it auto-loads or something I haven't used this in a while. (I am using 0.23 (Latest Ver.)

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 548, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 93, in get_players
  File "build\assets\species.py", line 335, in render_player
  File "build\assets\species.py", line 224, in render_chest
TypeError: 'NoneType' object is not subscriptable

2). I also tried running in administrative & I got the same error. 

Note: If this is Auto loading I will post another comment when I try to load this w/o my armour on like you have advised.

**Comment by wizzomafizzo** [comment]
hi. yep this is defnitely the same issue. i've actually already fixed it in the dev branch but i'm waiting to get a fix in for issue #191 before i do a new release,hoping for this weekend.

in the meantime you're free to do your own build of the dev branch or just unequip all your armour before you edit your character in starcheat
