### ISSUE TITLE
Crash when reading player files

### ISSUE THREAD

**Issue by Rensay** [wizzomafizzo/starcheat#193]
Hi as the heading implies I keep getting a crash when starcheat try's to read player files.
I'm running the latest version of starcheat and starbound with a select few mods.

Here are the details

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 548, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 93, in get_players
  File "build\assets\species.py", line 335, in render_player
  File "build\assets\species.py", line 241, in render_chest
  File "build\assets\images.py", line 27, in get_image
IndexError: list index out of range

Please help

**Comment by wizzomafizzo** [comment]
Hi. This is due to a bug with previewing armour on players. I'm going to get out a hotfix soonish to fix it, in the mean time the old version of starcheat will keep working fine.

**Comment by Rensay** [comment]
Thanks mate I will eagerly wait for the update

**Comment by wizzomafizzo** [comment]
No worries. Btw you should be able to continue using starcheat if you unequip your armour before starting it. Everything should work fine as long as you don't equip the "gender neutral" armours.

**Comment by wizzomafizzo** [comment]
Hi. Did the latest release (0.24) fix this for you?

**Comment by Rensay** [comment]
I got this

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 547, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 93, in get_players
  File "build\assets\species.py", line 345, in render_player
  File "build\assets\species.py", line 251, in render_chest
  File "build\assets\images.py", line 27, in get_image
IndexError: list index out of range
 
:(

**Comment by wizzomafizzo** [comment]
ahh man that sucks, i thought it would have picked that up. could you try load the player again but with the armour taken off (do it from Starbound) and see if it loads ok. i wanna make sure i'm on the right track and which armour exactly is causing it

if you're not sure which player is doing it upload a copy of your full starcheat log and i can tell you

**Comment by Rensay** [comment]
yeah it loaded up just fine once I removed my armour.
also I only have the one player and im using the Unofficial avali 1.3.3 mod plus a few related mods, if that helps

**Comment by wizzomafizzo** [comment]
Hi guys could you please confirm if the newest release (0.25) fixes this? I've added a workaround so it should no longer crash the whole app, it just ignore the item instead, but I'd still like to know which items don't show so I can eventually put in a real fix.
