### ISSUE TITLE
Starcheat crashes upon use.

### ISSUE THREAD

**Issue by Blizzaru** [wizzomafizzo/starcheat#196]
That's what I get :x
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 548, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 91, in get_players
  File "build\saves.py", line 461, in __init__
  File "build\saves.py", line 512, in import_save
  File "build\saves.py", line 384, in __init__
  File "build\saves.py", line 392, in import_metadata
  File "build\saves.py", line 301, in unpack_var
  File "build\saves.py", line 261, in unpack_starsave
  File "build\saves.py", line 221, in unpack_variant
TypeError: 'NoneType' object is not callable

**Comment by wizzomafizzo** [comment]
Hi. Could you please upload a copy of your starcheat log for me to look at. Instructions are here: https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs

I might also need you to upload your player files too but I'll let you know after I see the log.

**Comment by Blizzaru** [comment]
https://www.dropbox.com/s/o96fsyisk9uihpc/starcheat.log?dl=0
https://www.dropbox.com/s/slwqz70kmkqposz/starcheat.log.1?dl=0

**Comment by Blizzaru** [comment]
One of my characters didn't even show up on the program before (His ship was corrupted so I had to recover him) but the program worked just fine. This time - my computer crashed and one of my characters vanished from the game completely, this happened right after.

**Comment by wizzomafizzo** [comment]
I think it might just be because your computer crashed and the save was corrupted, don't think there's anything I'll be able to do to fix it sorry. The file that's tripping it up is:

e5ac5a087f65da98214f4f25875ce3ba.player

**Comment by Blizzaru** [comment]
It's working now, thank you. Although I had to delete my character for it.

**Comment by wizzomafizzo** [comment]
np. sorry about that but nothing really you can do in this situation besides hope there was a backup :(
