### ISSUE TITLE
Support for Pleased Giraffe.

### ISSUE THREAD

**Issue by thakyZ** [wizzomafizzo/starcheat#205]
I would like to have support for pleased giraffe on the dev branch because I cannot use anything else to edit with my inventory...
Thanks!

**Comment by TheAleG** [comment]
Traceback (most recent call last):
  File "C:\Starcheat\build\starcheat.py", line 83, in <module>
    main()
  File "C:\Starcheat\build\starcheat.py", line 80, in main
    gui.mainwindow.MainWindow()
  File "C:\Starcheat\build\gui\mainwindow.py", line 180, in __init__
    open_player = self.open_file()
  File "C:\Starcheat\build\gui\mainwindow.py", line 558, in open_file
    self.update()
  File "C:\Starcheat\build\gui\mainwindow.py", line 222, in update
    self.update_stat("health")
  File "C:\Starcheat\build\gui\mainwindow.py", line 830, in update_stat
    current = int(getattr(self.player, "get_"+name)())
  File "C:\Starcheat\build\saves.py", line 544, in get_health
    health = status["resourcePercentages"]["health"]
KeyError: 'resourcePercentages'

**Comment by wizzomafizzo** [comment]
I'll check how much work it would be to put out a special dev release but it depends how far away unstable goes to stable. I guess they changed something with how the stats work.

**Comment by MasemuneJM** [comment]
Good to know, waiting patiently
