### ISSUE TITLE
Latest stable update - Crash report

### ISSUE THREAD

**Issue by Xirukai** [wizzomafizzo/starcheat#208]
Crash report of the latest stable release of SB opened with Starcheat. Hoping it'll help out.

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 558, in open_file
  File "build\gui\mainwindow.py", line 222, in update
  File "build\gui\mainwindow.py", line 830, in update_stat
  File "build\saves.py", line 544, in get_health
KeyError: 'resourcePercentages'

**Comment by Gwynova** [comment]
Any word on a fix? im getting this error as well.. :v

**Comment by Xirukai** [comment]
An always wait for a fix! Havent heard anything, just hoped to help out by posting this crash report.

**Comment by wizzomafizzo** [comment]
i will try get a release out very soon. some very nice and probably handsome person just submitted a patch to fix this. i just need to do a quick test and shoot off the build scripts

**Comment by Gwynova** [comment]
Alright wonderful! Its much appreciated x3 also, where would i need to go for the patched ver when its avalible?

**Comment by Xirukai** [comment]
In stable build release, main page.

**Comment by Xirukai** [comment]
Be sure that the supplied update doesnt contain malicious coding or anything.

**Comment by Gwynova** [comment]
by chance do you have a link? i cant seem to find it ^^U

**Comment by Xirukai** [comment]
Issue fixed. No need to keep this active anymore.
