### ISSUE TITLE
Error with Please Giraffe 

### ISSUE THREAD

**Issue by XxArmaxX** [wizzomafizzo/starcheat#213]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 558, in open_file
  File "build\gui\mainwindow.py", line 222, in update
  File "build\gui\mainwindow.py", line 830, in update_stat
  File "build\saves.py", line 544, in get_health
KeyError: 'resourcePercentages'

**Comment by MasemuneJM** [comment]
Same get "
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 166, in __init__
  File "build\gui\mainwindow.py", line 491, in open_file
  File "build\gui\mainwindow.py", line 208, in update
  File "build\gui\mainwindow.py", line 711, in update_stat
  File "build\saves.py", line 545, in get_health
KeyError: 'resourcePercentages'
"

**Comment by Xirukai** [comment]
With the new version?

**Comment by XxArmaxX** [comment]
Ah, lemme see, wasnt out when this happened.

**Comment by XxArmaxX** [comment]
Ah, new version fixed it

**Comment by Gwynova** [comment]
Mine dosnt come up with an error anymore, but after editing my character, starbound crashes now -3-

**Comment by wizzomafizzo** [comment]
is the error reported originally fixed for you guys now?

@Gwynova could be a lot of different things not necessarily related to starcheat. you'll need to post a screenshot of the error message starbound gives you if you want to troubleshoot

**Comment by XxArmaxX** [comment]
@wizzomafizzo for me, yes
