### ISSUE TITLE
Crash on reading player files

### ISSUE THREAD

**Issue by B1polarb3ar** [wizzomafizzo/starcheat#216]
Logs:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 547, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 338, in render_player
  File "build\saves.py", line 694, in get_visible
KeyError: '__content'

Running Windows 10 64-bit
Starcheat version .26
Starbound version Pleased Giraffe - Update 3
tried running it in admin and compatibility with both Win7 and 8, no luck.

**Comment by wizzomafizzo** [comment]
could you please upload a copy of your player files. seems to be a slot in there with a weird item

**Comment by B1polarb3ar** [comment]
Welp, when i went to go upload the player file i noticed there were two player files and i had only made one player, i purged the folder and re-made my character and it seems to work fine now. Must have been an old character from a previous save. Thanks for responding!
