### ISSUE TITLE
Windows crash

### ISSUE THREAD

**Issue by DarkFlareMC707** [wizzomafizzo/starcheat#217]
This is what it says:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 559, in open_file
  File "build\gui\mainwindow.py", line 222, in update
  File "build\gui\mainwindow.py", line 831, in update_stat
  File "build\saves.py", line 544, in get_health
KeyError: 'resourcePercentages'

**Comment by DarkFlareMC707** [comment]
Using wrong version this entire time
