### ISSUE TITLE
Pleased Giraffe Update 3 report

### ISSUE THREAD

**Issue by OrbitalMan** [wizzomafizzo/starcheat#218]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 558, in open_file
  File "build\gui\mainwindow.py", line 222, in update
  File "build\gui\mainwindow.py", line 830, in update_stat
  File "build\saves.py", line 544, in get_health
KeyError: 'resourcePercentages'

**Comment by OrbitalMan** [comment]
OMG exuse me, I was wrong. Iэму launched v0.25 that time... (so stupid lol)
