### ISSUE TITLE
Crash when opening

### ISSUE THREAD

**Issue by Scienziatogm** [wizzomafizzo/starcheat#224]
Hi, I'm getting a crash when opening starcheat.
This is the log:

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 547, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 341, in render_player
  File "build\saves.py", line 694, in get_visible
KeyError: '__content'

**Comment by chrmoritz** [comment]
Starcheat crashes while generated the preview images for the select player dialog. This you have multiple causes:
* There is still an old character file from an outdated Starbound version in your `player` folder.
   * Check your `player` folder and remove all outdated saves from it.
* One of your players is wearing a corrupted item.
  * Move all player files outside the `player` folder and move them in again one by one (and open Starcheat to see if it still crashes) to determine which player file is causing the crash. Then check which of the items equipped by this character could have caused the crash and unequip it and store it in a chest outside the inventory.

**Comment by Scienziatogm** [comment]
Done. Now it's working.
