### ISSUE TITLE
if you have time ,please check this error

### ISSUE THREAD

**Issue by ruizhipeng** [wizzomafizzo/starcheat#225]
Traceback (most recent call last):
  File "/usr/share/starcheat/starcheat.py", line 83, in <module>
    main()
  File "/usr/share/starcheat/starcheat.py", line 80, in main
    gui.mainwindow.MainWindow()
  File "/usr/share/starcheat/gui/mainwindow.py", line 180, in __init__
    open_player = self.open_file()
  File "/usr/share/starcheat/gui/mainwindow.py", line 558, in open_file
    self.update()
  File "/usr/share/starcheat/gui/mainwindow.py", line 222, in update
    self.update_stat("health")
  File "/usr/share/starcheat/gui/mainwindow.py", line 830, in update_stat
    current = int(getattr(self.player, "get_"+name)())
  File "/usr/share/starcheat/saves.py", line 544, in get_health
    health = status["resourceValues"]["health"]
KeyError: 'resourceValues'

**Comment by ruizhipeng** [comment]
By the way my system is Arch and my package  is upgrade from the AUR

**Comment by chrmoritz** [comment]
The current starcheat version (0.26) only supports Starbound Pleased Giraffe. If you want to use it with older player files you have to use an older starcheat version.

**Comment by ruizhipeng** [comment]
thx,now i understand
