### ISSUE TITLE
Crash while reading player files

### ISSUE THREAD

**Issue by lego290** [wizzomafizzo/starcheat#226]
Starcheat crashes while loading, giving me this error:
```
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 547, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 280, in render_player
  File "C:\Python34-x64\lib\site-packages\PIL\Image.py", line 2330, in open
OSError: cannot identify image file <_io.BytesIO object at 0x0000000005E53768>
```

**Comment by chrmoritz** [comment]
It crashes while generating the preview image of a character with a modded species. It can't find the asserst for the species in the db and there the fallback image is missing in recent Starbound versions (or starcheat didn't updated to a path change of it).
Could you please try to:
* Rebuild your asserts: https://github.com/wizzomafizzo/starcheat/wiki/Rebuild-asset-index
* Reset all settings if this doesn't help: https://github.com/wizzomafizzo/starcheat/wiki/help#reset-all-settings
* or temporary move the character with the modded species out of the player folder as a workaround

**Comment by wizzomafizzo** [comment]
closing for now. please let us know if this issue is still happening and i will reopen
