### ISSUE TITLE
Starcheat 0.26 crashes on reading player files

### ISSUE THREAD

**Issue by Samiam955** [wizzomafizzo/starcheat#231]
Ever since I created a novakid character I've been having consistent crashes on around 70% through reading the player files, even after deleting the novakid character.

I get this error in the logs,

<spoiler> Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 547, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 105, in get_players
  File "build\saves.py", line 461, in __init__
  File "build\saves.py", line 512, in import_save
  File "build\saves.py", line 384, in __init__
  File "build\saves.py", line 392, in import_metadata
  File "build\saves.py", line 301, in unpack_var
  File "build\saves.py", line 261, in unpack_starsave
  File "build\saves.py", line 221, in unpack_variant
TypeError: 'NoneType' object is not callable </spoiler>

**Comment by wizzomafizzo** [comment]
hi. hard to say from the trimmed error message, we'll need a copy of the full log to see exactly what's going on. can you give us a copy of it with these instructions: https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs

the full log should say exactly which file is causing the problem but in the mean time you can try moving them out one by one until it works. if you do find the save file that's causing the problem could you please upload a copy of that too (somewhere like dropbox/mega)

**Comment by Samiam955** [comment]
The log itself is too large for recommended pastebin sites, so heres a link to download it.

https://www.dropbox.com/s/hs50vo010s8y5yk/starcheat.log?dl=0

**Comment by wizzomafizzo** [comment]
Player file causing the crash is: d0a8080c918afc3a2005a62e6263471c.player

These ones also seem to be corrupt/incompatible from starcheat's perspective, but are being skipped correctly:
- a09161faa25db0aa73663127ec987467.player
- 4aae95a0dcdc8b9944f513d3e1ad5cbc.player
- 151c6417b749a1b7755258621f5a4f9b.player
- 128be182d4c13be6b16176631dd8e782.player

We're only really interested in that first one to stop the crashing though.

**Comment by Samiam955** [comment]
Removing the said file fixed the crashing, thank you!

**Comment by Samiam955** [comment]
Oh, and here is the file. https://www.dropbox.com/s/2guan1xrbl8t8up/d0a8080c918afc3a2005a62e6263471c.player?dl=0
