### ISSUE TITLE
New Starbound save file version! YAY!

### ISSUE THREAD

**Issue by thakyZ** [wizzomafizzo/starcheat#232]
So, unstable build of Starbound came out not to long ago, and everything thing was fine, but then a new save file version came out, so you know what that mean, everything is broke.
This is a list of what I know is broken so far:
- Player armor images don't load correctly - All inventory tabs and hotbar and hand slots are broken (even with the object tab being enabled from that pull request) - and stats are broken -

That is all I have for now.
BTW the new ID for the Starbound version is ```SBVJ01```

**Comment by wizzomafizzo** [comment]
Hey. Thanks for letting me know. I'll see how I go with it... haven't been motivated at all to work on this stuff lately, hopefully they take a while to get this into stable.

**Comment by j4ck-no1r** [comment]
I'll take a look when I get home.

**Comment by thakyZ** [comment]
@j4ck-no1r I don't know if you tested your commit but it's broken with this error:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 558, in open_file
  File "build\gui\mainwindow.py", line 263, in update
  File "build\gui\mainwindow.py", line 741, in update_bag
  File "build\gui\common.py", line 116, in __init__
  File "build\gui\common.py", line 63, in inv_icon
  File "build\assets\items.py", line 137, in get_item_icon
TypeError: argument of type 'NoneType' is not iterable

**Comment by thakyZ** [comment]
Here is the log:
http://pastebin.com/9VJcafBR

**Comment by j4ck-no1r** [comment]
Looking through that log, it looks like the issue is with a modded item, "voidexcalibur.activeitem" from LillyMod. If you wouldn't mind sending me the mod, I could take a look.

**Comment by thakyZ** [comment]
That is one of my personal items I probably messed up on something but you can look at the mod here: https://github.com/thakyZ/LillyMod

**Comment by thakyZ** [comment]
I just tried wizzomafizzo's build and it works now but it may be because I also deleted the assets.db file from appdata/roaming/starcheat
