### ISSUE TITLE
starcheat crashing 

### ISSUE THREAD

**Issue by ButterSensei** [wizzomafizzo/starcheat#235]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 547, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 339, in render_player
  File "build\saves.py", line 694, in get_visible
KeyError: '__content'

^that's the stuff the app told me to paste in.

**Comment by j4ck-no1r** [comment]
Glad Giraffe changed the item format in player files. A new release of Starcheat that works for Glad Giraffe is being worked on and will hopefully be out shortly.

**Comment by Vejyl** [comment]
Please Girafe 

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 547, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 338, in render_player
  File "build\saves.py", line 692, in get_visible
KeyError: '__content'

**Comment by wizzomafizzo** [comment]
closing for now. please let us know if this issue is still happening and i will reopen. pretty sure this is fixed in latest starcheat though
