### ISSUE TITLE
Issue Launching

### ISSUE THREAD

**Issue by Diiax** [wizzomafizzo/starcheat#236]
64 bit OpenGL
Version 0.26
Windows 7

Download : starcheat-0.26-win64.zip

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 547, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 339, in render_player
  File "build\saves.py", line 694, in get_visible
KeyError: '__content'

**Comment by j4ck-no1r** [comment]
Starcheat 0.26 does not work with Glad Giraffe. A new version that does is being worked on.

**Comment by Diiax** [comment]
Thanks, I just read. Sorry to waste your time.

**Comment by wizzomafizzo** [comment]
dw you're not wasting anyone's time. thanks for the report anyway, appreciated
