### ISSUE TITLE
Crash on startup:

### ISSUE THREAD

**Issue by IIEclipseDII** [wizzomafizzo/starcheat#238]
---------------------------

---------------------------
Oops, starcheat has crashed.
---------------------------

<html><head/><body>
<p>To report this error, click <strong>Show Details...</strong> and post the crash report it displays to the <a href="https://github.com/wizzomafizzo/starcheat">starcheat GitHub</a>.</p>
</body></html>

---------------------------
OK   Hide Details...   
---------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 547, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 339, in render_player
  File "build\saves.py", line 694, in get_visible
KeyError: '__content'

---------------------------

**Comment by Xirukai** [comment]
It is being worked on, please be patient.

**Comment by IIEclipseDII** [comment]
Got it.

**Comment by wizzomafizzo** [comment]
closing for now. please let us know if this issue is still happening and i will reopen. should be fixed in latest starcheat
