### ISSUE TITLE
Crash when opening

### ISSUE THREAD

**Issue by HomingJoker** [wizzomafizzo/starcheat#239]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 176, in __init__
  File "build\gui\mainwindow.py", line 542, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 339, in render_player
  File "build\saves.py", line 620, in get_visible
KeyError: 'content'

**Comment by Xirukai** [comment]
@HomingJoker Be sure to go into singleplayer with each character to allow the metadata merge with the player file. After you did that it should work.

**Comment by HomingJoker** [comment]
works now thanks :D
