### ISSUE TITLE
Crash Upon Loading 50%

### ISSUE THREAD

**Issue by Raylo555** [wizzomafizzo/starcheat#240]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 176, in __init__
  File "build\gui\mainwindow.py", line 542, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 339, in render_player
  File "build\saves.py", line 622, in get_visible
KeyError: 'content'

what does mean? (not a programmer at all)

**Comment by Raylo555** [comment]
nvm, opened all players and fixed it
