### ISSUE TITLE
Crashing upon loading

### ISSUE THREAD

**Issue by Kaitnoday** [wizzomafizzo/starcheat#241]
This is the crash report details:

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 176, in __init__
  File "build\gui\mainwindow.py", line 542, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 338, in render_player
  File "build\saves.py", line 622, in get_visible
KeyError: 'content'

**Comment by iStormUK** [comment]
Same here: 
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 176, in __init__
  File "build\gui\mainwindow.py", line 542, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 338, in render_player
  File "build\saves.py", line 622, in get_visible
KeyError: 'content'

**Comment by Xirukai** [comment]
Could either of you post your old character files from please giraffe? See if there could be a hotfix made.

**Comment by Kaitnoday** [comment]
Here, https://drive.google.com/file/d/0BxvWxHYd8KMRYVVXRlhwVHA1aEE/view?usp=sharing

**Comment by wizzomafizzo** [comment]
hi. could you please give the latest release 0.27.1 a try and let me know if it works any better

**Comment by wizzomafizzo** [comment]
closing for now. please let us know if this issue is still happening and i will reopen
