### ISSUE TITLE
first time start up crashes(ive tried to redownload.

### ISSUE THREAD

**Issue by digimoto** [wizzomafizzo/starcheat#242]
i get this error http://pastebin.com/j4KfMjcb

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 164, in __init__
  File "build\assets\species.py", line 51, in get_species_list
sqlite3.OperationalError: no such table: assets

**Comment by wizzomafizzo** [comment]
could you please try this and let me know how you go: https://github.com/wizzomafizzo/starcheat/wiki/help#reset-all-settings

sounds like the database is corrupt, it's a bit hidden away but it's safe to delete

**Comment by digimoto** [comment]
it works now thanks I think it was due to having some broken item in my characters so, I deleted them aswell and it worked.

**Comment by wizzomafizzo** [comment]
cool. thanks for the report!
