### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by Alhrguy** [wizzomafizzo/starcheat#244]
I've updated all my characters, uninstalled any mods, tried deleting and reinstalling starcheat, deleting the assets.db and starcheat.ini

No matter what I do, I get this.

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 176, in __init__
  File "build\gui\mainwindow.py", line 542, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 338, in render_player
  File "build\saves.py", line 620, in get_visible
KeyError: 'content'

**Comment by TheElderScroller** [comment]
same error on my second PC, on my first it works now, but I don't know what fixed it.

**Comment by wizzomafizzo** [comment]
hi. could you please give the latest release 0.27.1 a try and let me know if it works any better

**Comment by Alhrguy** [comment]
0.27.1 Works. Dunno what the problem was, but it got fixed, apparently.
