### ISSUE TITLE
Starcheat startup crash

### ISSUE THREAD

**Issue by Donteros** [wizzomafizzo/starcheat#245]
It keeps crashing on startup, here is the response I got:

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 176, in __init__
  File "build\gui\mainwindow.py", line 542, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 338, in render_player
  File "build\saves.py", line 620, in get_visible
KeyError: 'content'

**Comment by wizzomafizzo** [comment]
hi. could you please give the latest release 0.27.1 a try and let me know if it works any better

**Comment by Donteros** [comment]
Yeah it works now, thanks alot!

**Comment by wizzomafizzo** [comment]
sweet. thanks for the report
