### ISSUE TITLE
Crashing with .27

### ISSUE THREAD

**Issue by ButterSensei** [wizzomafizzo/starcheat#246]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 176, in __init__
  File "build\gui\mainwindow.py", line 542, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 338, in render_player
  File "build\saves.py", line 620, in get_visible
KeyError: 'content'

**Comment by wizzomafizzo** [comment]
hi could you please post a full log for me as well. instruction are here: https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs

**Comment by ButterSensei** [comment]
there is no starcheat log file?

**Comment by ButterSensei** [comment]
![image](https://cloud.githubusercontent.com/assets/16216069/11885624/5d2f2b88-a4de-11e5-8521-bbec3e554eab.png)

**Comment by chrmoritz** [comment]
you have selected it in your screenshot

BTW: Do your self a favor and unhide file extensions in windows explorer.

**Comment by ButterSensei** [comment]
2015-12-18 14:55:28,177 INFO     starcheat init
2015-12-18 14:55:28,177 INFO     Version: 0.27 (Glad Giraffe)
2015-12-18 14:55:28,177 INFO     Platform: Windows
2015-12-18 14:55:28,178 INFO     Checking for updates
2015-12-18 14:55:28,855 INFO     Main window init
2015-12-18 14:55:28,856 DEBUG    Setting up wieldable bag
2015-12-18 14:55:28,859 DEBUG    Setting up head bag
2015-12-18 14:55:28,863 DEBUG    Setting up chest bag
2015-12-18 14:55:28,866 DEBUG    Setting up legs bag
2015-12-18 14:55:28,870 DEBUG    Setting up back bag
2015-12-18 14:55:28,870 DEBUG    Setting up main_bag bag
2015-12-18 14:55:28,877 DEBUG    Setting up action_bar bag
2015-12-18 14:55:28,880 DEBUG    Setting up object_bag bag
2015-12-18 14:55:28,888 DEBUG    Setting up tile_bag bag
2015-12-18 14:55:28,891 DEBUG    Setting up essentials bag
2015-12-18 14:55:28,892 DEBUG    Setting up mouse bag
2015-12-18 14:55:28,903 DEBUG    Showing main window
2015-12-18 14:55:29,137 INFO     First setup dialog
2015-12-18 14:55:30,020 INFO     update check: found new starcheat version
2015-12-18 14:55:30,846 INFO     Scanning vanilla assets
2015-12-18 14:55:31,122 INFO     Creating new assets index...
2015-12-18 14:55:31,122 INFO     Scanning vanilla assets
2015-12-18 14:55:31,461 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/gun.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:31,477 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/hammer/shockwave/shockwave.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:31,831 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/homingrocket/homingrocket.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:32,013 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/broadsword/downstab/downstab.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:32,035 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/hammer/hammer.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:32,068 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/hammer/elementalpillar/elementalpillar.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:32,367 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/hammer/uppercut/uppercut.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:32,895 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/broadsword/parry/parry.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:32,948 WARNING  Skipping invalid item asset (no name set) /items/active/unsorted/wateringcan/wateringcan.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:33,126 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/broadsword/giantsword/giantsword.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:33,146 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/chakram/chakram.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:33,164 WARNING  Skipping invalid item asset (no name set) /items/active/unsorted/rewardbag/rewardbag.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:33,999 WARNING  Skipping invalid item asset (no name set) /items/active/unsorted/parasol/parasol.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:34,004 WARNING  Skipping invalid item asset (no name set) /items/active/vehiclecontroller/vehiclecontroller.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:34,024 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/spear/spear.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:34,100 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/remotegrenadelauncher/remotegrenadelauncher.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:34,150 WARNING  Skipping invalid item asset (no name set) /items/active/shields/shield.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:34,411 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/fist/combofinishers/snaproot.combofinisher in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:35,074 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/spray/spray.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:35,139 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/spear/barrier/barrier.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:35,158 ERROR    Unable to read db asset '/monsters/dungeon/glitchspider/default.frames' from 'C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak'
Traceback (most recent call last):
  File "build\assets\core.py", line 239, in read
  File "build\assets\core.py", line 41, in parse_json
  File "C:\Python34-x64\lib\json\decoder.py", line 343, in decode
  File "C:\Python34-x64\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
2015-12-18 14:55:35,767 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/shrapnelbomb/shrapnelbomb.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:35,954 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/hammer/shockwave/physicalshockwave.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:36,252 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/spear/charge/charge.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:36,394 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/broadsword/risingslash/risingslash.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:36,409 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/generic/blinkslash/blinkslash.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:36,879 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/lance/lance.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:36,987 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/hammer/elementalaura/elementalaura.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:37,028 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/explosiveburst/explosiveburst.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:37,036 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/deathbomb/deathbomb.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:37,169 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/generic/blinkexplosion/blinkexplosion.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:37,547 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/piercingshot/piercingshot.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:37,676 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/hammer/tieredhammer.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:37,688 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/axe/axe.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:37,933 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/burstshot/burstshot.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:38,453 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/broadsword/bladecharge/bladecharge.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:39,410 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/grenadelauncher/grenadelauncher.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:39,446 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/markedshot/markedshot.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:39,632 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/fist/combofinishers/powerpunch.combofinisher in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:39,999 WARNING  Skipping invalid item asset (no name set) /items/active/unsorted/translocator/translocator.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:40,900 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/dagger/dagger.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:41,788 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/spear/flurry/flurry.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:42,138 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/stickyshot/stickyshot.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:42,176 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/fist/combofinishers/uppercut.combofinisher in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:42,710 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/fist/vinefist.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:42,745 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/broadsword/broadsword.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:43,146 WARNING  Skipping invalid item asset (no name set) /items/active/grapple/grapple.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:43,160 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/spear/rocketspear/rocketspear.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:43,405 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/broadsword/spinslash/spinslash.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:43,417 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/broadsword/travelingslash/travelingslash.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:43,498 ERROR    Unable to read db asset '/objects/wired/invisiblesound/invisiblesoundhidden.frames' from 'C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak'
Traceback (most recent call last):
  File "build\assets\core.py", line 239, in read
  File "build\assets\core.py", line 41, in parse_json
  File "C:\Python34-x64\lib\json\decoder.py", line 343, in decode
  File "C:\Python34-x64\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 7 column 5 (char 127)
2015-12-18 14:55:43,771 WARNING  Skipping invalid item asset (no name set) /items/active/unsorted/partypopper/partypopper.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:43,832 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/hammer/groundslam/groundslam.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:44,861 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/flashlight/flashlight.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:44,987 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/boomerang/boomerang.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:46,063 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/bouncingshot/bouncingshot.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:46,535 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/shortsword/shortsword.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:46,802 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/guidedrocket/guidedrocket.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:46,898 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/broadsword/spinslash/superspinslash.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:50,223 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/spear/tieredspear.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:50,551 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/spear/spin/spin.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:51,173 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/broadsword/traildash/traildash.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:51,365 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/fuelairtrail/fuelairtrail.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:51,492 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/fist/fistweapon.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:51,588 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/broadsword/tieredbroadsword.animation in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:52,347 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/fist/combofinishers/thunderpunch.combofinisher in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:52,367 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/fist/combofinishers/dashslash.combofinisher in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:52,435 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/explosiveshot/explosiveshot.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:54,182 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/ranged/altabilities/rocketburst/rocketburst.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:54,291 WARNING  Skipping invalid item asset (no name set) /items/active/weapons/melee/altabilities/spear/elementalspin/elementalspin.altability in C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets\packed.pak
2015-12-18 14:55:54,593 INFO     Finished creating index
2015-12-18 14:55:54,618 INFO     Starbound folder: C:\Program Files (x86)\Steam\SteamApps\common\Starbound
2015-12-18 14:55:54,618 INFO     Checking assets hash
2015-12-18 14:55:54,620 INFO     Loading assets database
2015-12-18 14:55:54,671 DEBUG    Open file dialog
2015-12-18 14:55:54,681 DEBUG    Init save import: C:\Program Files (x86)\Steam\SteamApps\common\Starbound\giraffe_storage\player\4ccd41d8ac12356699db1067ce3fcc07.player
2015-12-18 14:55:54,869 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:54,869 DEBUG    STREAM b'IDAT' 41 7765
2015-12-18 14:55:54,879 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:54,879 DEBUG    STREAM b'IDAT' 41 4780
2015-12-18 14:55:54,888 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:54,888 DEBUG    STREAM b'IDAT' 41 4592
2015-12-18 14:55:54,897 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:54,897 DEBUG    STREAM b'IDAT' 41 608
2015-12-18 14:55:54,952 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:54,952 DEBUG    STREAM b'IDAT' 41 799
2015-12-18 14:55:55,062 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:55,062 DEBUG    STREAM b'IDAT' 41 4245
2015-12-18 14:55:55,262 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:55,262 DEBUG    STREAM b'IDAT' 41 5700
2015-12-18 14:55:55,374 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:55,374 DEBUG    STREAM b'IDAT' 41 914
2015-12-18 14:55:55,528 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:55,529 DEBUG    STREAM b'IDAT' 41 4648
2015-12-18 14:55:55,594 DEBUG    Init save import: C:\Program Files (x86)\Steam\SteamApps\common\Starbound\giraffe_storage\player\909f1bbac808ede899fa5cf8b82b704e.player
2015-12-18 14:55:55,880 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:55,881 DEBUG    STREAM b'IDAT' 41 7765
2015-12-18 14:55:55,889 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:55,890 DEBUG    STREAM b'IDAT' 41 4780
2015-12-18 14:55:55,898 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:55,899 DEBUG    STREAM b'IDAT' 41 4592
2015-12-18 14:55:55,907 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:55,907 DEBUG    STREAM b'IDAT' 41 608
2015-12-18 14:55:55,961 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:55,961 DEBUG    STREAM b'IDAT' 41 823
2015-12-18 14:55:56,069 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:56,069 DEBUG    STREAM b'IDAT' 41 860
2015-12-18 14:55:56,266 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:56,266 DEBUG    STREAM b'IDAT' 41 4250
2015-12-18 14:55:56,417 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:56,417 DEBUG    STREAM b'IDAT' 41 5975
2015-12-18 14:55:56,524 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:56,525 DEBUG    STREAM b'IDAT' 41 1900
2015-12-18 14:55:56,673 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:56,674 DEBUG    STREAM b'IDAT' 41 860
2015-12-18 14:55:56,867 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:55:56,867 DEBUG    STREAM b'pHYs' 41 9
2015-12-18 14:55:56,868 DEBUG    STREAM b'iTXt' 62 14373
2015-12-18 14:55:56,868 DEBUG    STREAM b'cHRM' 14447 32
2015-12-18 14:55:56,868 DEBUG    b'cHRM' 14447 32 (unknown)
2015-12-18 14:55:56,868 DEBUG    STREAM b'IDAT' 14491 491
2015-12-18 14:55:56,870 DEBUG    Init save import: C:\Program Files (x86)\Steam\SteamApps\common\Starbound\giraffe_storage\player\95628452f3566ff16417039191054e44.player
2015-12-18 14:56:07,701 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:07,701 DEBUG    STREAM b'IDAT' 41 7234
2015-12-18 14:56:07,711 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:07,711 DEBUG    STREAM b'IDAT' 41 4780
2015-12-18 14:56:07,721 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:07,721 DEBUG    STREAM b'IDAT' 41 4592
2015-12-18 14:56:07,731 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:07,732 DEBUG    STREAM b'IDAT' 41 608
2015-12-18 14:56:07,797 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:07,797 DEBUG    STREAM b'IDAT' 41 408
2015-12-18 14:56:07,949 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:07,949 DEBUG    STREAM b'IDAT' 41 1687
2015-12-18 14:56:08,200 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:08,200 DEBUG    STREAM b'IDAT' 41 6820
2015-12-18 14:56:08,369 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:08,370 DEBUG    STREAM b'pHYs' 41 9
2015-12-18 14:56:08,370 DEBUG    STREAM b'iTXt' 62 15238
2015-12-18 14:56:08,370 DEBUG    STREAM b'cHRM' 15312 32
2015-12-18 14:56:08,370 DEBUG    b'cHRM' 15312 32 (unknown)
2015-12-18 14:56:08,370 DEBUG    STREAM b'IDAT' 15356 6374
2015-12-18 14:56:08,491 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:08,491 DEBUG    STREAM b'IDAT' 41 1163
2015-12-18 14:56:08,676 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:08,676 DEBUG    STREAM b'IDAT' 41 2147
2015-12-18 14:56:08,888 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:08,888 DEBUG    STREAM b'pHYs' 41 9
2015-12-18 14:56:08,888 DEBUG    STREAM b'iTXt' 62 14800
2015-12-18 14:56:08,889 DEBUG    STREAM b'cHRM' 14874 32
2015-12-18 14:56:08,889 DEBUG    b'cHRM' 14874 32 (unknown)
2015-12-18 14:56:08,889 DEBUG    STREAM b'IDAT' 14918 690
2015-12-18 14:56:08,896 DEBUG    Init save import: C:\Program Files (x86)\Steam\SteamApps\common\Starbound\giraffe_storage\player\a6b0e5dee58608afc88813e1832242ed.player
2015-12-18 14:56:09,220 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:09,221 DEBUG    STREAM b'IDAT' 41 7234
2015-12-18 14:56:09,230 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:09,230 DEBUG    STREAM b'IDAT' 41 4780
2015-12-18 14:56:09,239 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:09,239 DEBUG    STREAM b'IDAT' 41 4592
2015-12-18 14:56:09,248 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:09,248 DEBUG    STREAM b'IDAT' 41 608
2015-12-18 14:56:09,302 DEBUG    STREAM b'IHDR' 16 13
2015-12-18 14:56:09,302 DEBUG    STREAM b'IDAT' 41 408
2015-12-18 14:56:09,308 DEBUG    Traceback (most recent call last):

2015-12-18 14:56:09,308 DEBUG      File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>

2015-12-18 14:56:09,308 DEBUG      File "build\starcheat.py", line 83, in <module>

2015-12-18 14:56:09,308 DEBUG      File "build\starcheat.py", line 80, in main

2015-12-18 14:56:09,308 DEBUG      File "build\gui\mainwindow.py", line 176, in __init__

2015-12-18 14:56:09,309 DEBUG      File "build\gui\mainwindow.py", line 542, in open_file

2015-12-18 14:56:09,309 DEBUG      File "build\gui\openplayer.py", line 58, in __init__

2015-12-18 14:56:09,309 DEBUG      File "build\gui\openplayer.py", line 107, in get_players

2015-12-18 14:56:09,309 DEBUG      File "build\assets\species.py", line 338, in render_player

2015-12-18 14:56:09,309 DEBUG      File "build\saves.py", line 620, in get_visible

2015-12-18 14:56:09,309 DEBUG    KeyError: 'content'

2015-12-18 14:56:09,310 DEBUG    Starbound folder: C:\Program Files (x86)\Steam\SteamApps\common\Starbound
2015-12-18 14:56:09,311 DEBUG    Assets folder: C:\Program Files (x86)\Steam\SteamApps\common\Starbound\assets
2015-12-18 14:56:09,312 DEBUG    Player folder: C:\Program Files (x86)\Steam\SteamApps\common\Starbound\giraffe_storage\player

**Comment by wizzomafizzo** [comment]
closing for now. please let us know if this issue is still happening and i will reopen. this should have been fixed in the latest version of starcheat
