### ISSUE TITLE
OH MAN I AM NOT GOOD WITH COMPUTER PLZ TO HELP

### ISSUE THREAD

**Issue by DrDolphinrider** [wizzomafizzo/starcheat#248]
Traceback (most recent call last):
  File "/Users/user/Downloads/StarCheat.app/Contents/Resources/__boot__.py", line 399, in <module>
  File "/Users/user/Downloads/StarCheat.app/Contents/Resources/__boot__.py", line 336, in _run
  File "/Users/user/Downloads/StarCheat.app/Contents/Resources/starcheat.py", line 74, in <module>
  File "/Users/user/Downloads/StarCheat.app/Contents/Resources/starcheat.py", line 71, in main
  File "gui/mainwindow.pyc", line 166, in __init__
  File "gui/mainwindow.pyc", line 491, in open_file
  File "gui/mainwindow.pyc", line 208, in update
  File "gui/mainwindow.pyc", line 711, in update_stat
  File "saves.pyc", line 545, in get_health
KeyError: 'resourcePercentages'

**Comment by thakyZ** [comment]
Please upload the log and paste the link here. (The log is located at C:\Users\YourUser\AppData\Roaming\starcheat\starcheat.log)

**Comment by thakyZ** [comment]
What version of starcheat are you using?

**Comment by wizzomafizzo** [comment]
here are instructions for getting mac logs too: https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs

haven't seen this in a while, so i'd say double check you're definitely running version 0.27.1, can check in the about window. the log will give more information though, might need a copy of your player file after

**Comment by wizzomafizzo** [comment]
please let me know if this is still broken for you
