### ISSUE TITLE
help me please ! i'm not good with program (bug)

### ISSUE THREAD

**Issue by nhoksieuquay** [wizzomafizzo/starcheat#250]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 176, in __init__
  File "build\gui\mainwindow.py", line 542, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 107, in get_players
  File "build\assets\species.py", line 338, in render_player
  File "build\saves.py", line 622, in get_visible
KeyError: 'content'
i tried reinstall but not work

**Comment by wizzomafizzo** [comment]
hi, are you using the unstable version of starbound? if not, could you run through these steps to upload a full log file, then we can track down the save file causing it: https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs

**Comment by wizzomafizzo** [comment]
please let me know if this is still an issue and i will reopen
