### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by TLNiles** [wizzomafizzo/starcheat#254]
No idea what could be a reason really. Crash happens at "Reading player files". Starcheat version used - 0.27.1, Starbound version - Glad Giraffe(Unstable Nightly).

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 176, in __init__
  File "build\gui\mainwindow.py", line 542, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 119, in get_players
  File "build\gui\openplayer.py", line 136, in populate
  File "build\saves.py", line 586, in get_play_time
KeyError: 'playTime'

**Comment by chrmoritz** [comment]
Unfortunately it's expected behavior to crash when trying to open an incompatible player save file (at least when the player format version it's still the same which is most likely the case because it's nightly).
So 0.28 will again include a new player file format.

**Comment by Xirukai** [comment]
Darn, hoping it gets fixed when the new update is pushed from CF.

**Comment by chrmoritz** [comment]
It gets either fixed when Starbound is finally updating their save file format version (than the incompatible save file will be successfully ignored and doesn't cause a crash anymore) or Starcheat gets updated to the new save file format version (but because they didn't update the version yet it looks like the new save format isn't finished yet).
