### ISSUE TITLE
27.1 Crashing on rebuilding assets index

### ISSUE THREAD

**Issue by PimpMyWhale** [wizzomafizzo/starcheat#259]
Downloaded the 27.1 update for Windows 64bit and when I go to rebuild the assets index, Starcheat crashes. I've tried re-installing Starcheat and that hasn't worked at all. The error message I get on crash is: Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 154, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 52, in build_assets_db
  File "build\assets\core.py", line 54, in __init__
sqlite3.OperationalError: unable to open database file

and the log is posted here: http://pastebin.com/NiWvAbYY

**Comment by chrmoritz** [comment]
You could try to [delete the database and the config file](https://github.com/wizzomafizzo/starcheat/wiki/help#reset-all-settings). Does this fix your issue?

**Comment by PimpMyWhale** [comment]
That completely fixes the problem! Thanks for your help!
