### ISSUE TITLE
Manage Blueprints crash

### ISSUE THREAD

**Issue by Sparksolur** [wizzomafizzo/starcheat#260]
Starcheat 27.1, running on the Stable.

On about half of my characters, both old ones and brand new (seems to be random on which ones are affected, but if they are then it is consistently the same characters affected) when I click the Manage Blueprints button, I get this:

Traceback (most recent call last):
  File "build\gui\mainwindow.py", line 455, in new_blueprint_edit
  File "build\gui\blueprints.py", line 44, in __init__
  File "build\gui\blueprints.py", line 22, in __init__
TypeError: 'NoneType' object is not subscriptable

**Comment by chrmoritz** [comment]
Do you have any mode installed which adds additional blueprints?
Also posting the complete log would help debugging this too: https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs

**Comment by Sparksolur** [comment]
Rather a lot, I'm afraid. I've been going through a large combination for playing on some servers to make sure my computer could run it all; I haven't even gotten to Frackin' Universe yet.

I'm honestly pleasantly surprised Starcheat was working at all with this mess.

My apologies for this: https://gist.github.com/Sparksolur/a65ed1e6eda8566b5d86

**Comment by chrmoritz** [comment]
Looks like mod support is slightly broken atm. I see a lot of these 2 errors while indexing your mods:

```
Traceback (most recent call last):
  File "build\assets\core.py", line 252, in read
  File "build\assets\core.py", line 46, in load_asset_file
  File "c:\Python\64-bit\3.4\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 44: character maps to <undefined>
```

```
Traceback (most recent call last):
  File "build\assets\core.py", line 252, in read
  File "build\assets\core.py", line 47, in load_asset_file
  File "build\assets\core.py", line 41, in parse_json
  File "C:\Python34-x64\lib\json\decoder.py", line 343, in decode
  File "C:\Python34-x64\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
```
cc @wizzomafizzo

**Comment by wizzomafizzo** [comment]
@Sparksolur can I grab a copy of the JSON export for one of the characters it's breaking on? (File > Expor t> Player JSON)

i suspect the problem with the json errors might be here:
https://github.com/wizzomafizzo/starcheat/blob/master/starcheat/assets/core.py#L45

pretty sure it defaults to ascii rather than utf8, so that might be what's breaking

@Sparksolur one of the files it breaks on is "\objects\felin\felingraffiti\felingraffiti4.object" are you able to give us a link of copy of this felin mod?

i'm not sure how all this fits into the blueprint window breaking though, still need to try out one of the broken characters

(also i found out all those STREAM lines in the logs are from pillow, nothing to worry about but not sure how to suppress them atm)

**Comment by chrmoritz** [comment]
@wizzomafizzo 
> (also i found out all those STREAM lines in the logs are from pillow, nothing to worry about but not sure how to suppress them atm)

Looks like Pillow has changed their logging code with the v3.0 release.
Prior to 3.0 it was [a simple print behind a Image.DEBUG flag](https://github.com/python-pillow/Pillow/blob/2.9.0/PIL/PngImagePlugin.py#L132-L133) (default to false), but since 3.0 it uses [pythons logging module](https://github.com/python-pillow/Pillow/blob/3.0.0/PIL/PngImagePlugin.py#L135).

**Comment by Sparksolur** [comment]
Here's the json: https://www.dropbox.com/s/r7epuhu5gndm6c2/Itemguy.json?dl=0

And here's a link to the felin mod: http://community.playstarbound.com/resources/felins.68/ 

If that one fails, this one should work: http://community.playstarbound.com/resources/felins.68/download?version=15032

**Comment by wizzomafizzo** [comment]
there is a null at the very end of the of the newBlueprints and knownBlueprints lists. are the players this is happening on new or from older versions?

**Comment by Sparksolur** [comment]
Made new in Glad Giraffe.
