### ISSUE TITLE
Manage your ship and AI

### ISSUE THREAD

**Issue by gabrielcnj** [wizzomafizzo/starcheat#271]
Traceback (most recent call last):
  File "build\gui\mainwindow.py", line 512, in new_ship_dialog
  File "build\gui\ship.py", line 32, in __init__
  File "build\gui\ship.py", line 39, in update
TypeError: QSpinBox.setValue(int): argument 1 has unexpected type 'NoneType'

**Comment by chrmoritz** [comment]
What version of Starbound and starcheat are you using?

**Comment by wizzomafizzo** [comment]
I can reproduce this in unstable with any player that hasn't gone through the initial "ship wake up" stuff
