### ISSUE TITLE
glad giraffe nightly crashing starcheat

### ISSUE THREAD

**Issue by starbounder** [wizzomafizzo/starcheat#274]
## Please follow these steps before opening a new issue:

* [ ] try updating starcheat to the [latest](https://github.com/wizzomafizzo/starcheat/releases/latest) version [compatible](https://github.com/wizzomafizzo/starcheat#downloads) with your Starbound version and retry (maybe your issue is already fixed)
* [ ] search [all open issues](https://github.com/wizzomafizzo/starcheat/issues?utf8=%E2%9C%93&q=is%3Aopen+) for issues similar to yours. If you find a issue matching yours consider commenting in this issue (and providing additional informations there) rather then opening a new one.
* [ ] if you think your issues isn't already reporting please open a new one and try to include as much details as possible describing your issue

## Issue details:pretty sure the new nightly crashes starcheat reset all settings and is working fine again for glad giraffe stable 
*Please try to fill out as many fields as you can below (by replacing the text between the two *).*

* .27.1: *insert starcheat version here (e.g. `0.27.1`)*
* glad giraffe / nightly (stable / unstable / nightly): *insert starbound version here (e.g. `Glad Giraffe (stable)` or `nightly`)*
* the error message your a getting if any: oops, starcheat has crashed
```
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 154, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 127, in find_assets
  File "build\assets\core.py", line 156, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

```
* a link to your starcheat log file: *insert link here (e.g. `https://gist.github.com/Sparksolur/a65ed1e6eda8566b5d86`)*
  * [read this wiki entry](https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs) for a guide how to get the logs
  * upload the log to somewhere, where we can access them (preferable [gist](https://gist.github.com/))
* if the issue is related to a player files please upload the affected player file somewhere if possible: *insert player file here*
* if the issue is related to a mod please link to the mod you are using if possible: *insert mod link here*

**Comment by chrmoritz** [comment]
Did they introduce a sbbf04 file format now? This needs to be fixed by https://github.com/blixt/py-starbound of we need to maintain our own fork. I hope the didn't changed to much like in the last sbbf update.

**Comment by wizzomafizzo** [comment]
@starbounder do you have a copy of the save file and are you using any mods? i've just tried starcheat with unstable and had no problems reading all the saves. not sure if it picked up less assets but it at least got most of them

**Comment by wizzomafizzo** [comment]
@chrmoritz unrelated but have you tried editing avians lately? i've just tried it now and the rendering is completely boned, but there are no errors and all the other races work

**Comment by wizzomafizzo** [comment]
I haven't even gotten as far as opening this thing up in a hex editor, has the nightly format been updated again from SBBF04? Unfortunately the fix for this wasn't as simple as just adding SBBF04 in the supported string list, but idk I might just be using the wrong string
