### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by SquishyMcDoodles** [wizzomafizzo/starcheat#281]
What do I do to fix the following issues?

**Comment by SquishyMcDoodles** [comment]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 176, in __init__
  File "build\gui\mainwindow.py", line 553, in open_file
  File "build\gui\mainwindow.py", line 259, in update
  File "build\gui\mainwindow.py", line 713, in update_bag
  File "build\gui\common.py", line 116, in __init__
  File "build\gui\common.py", line 63, in inv_icon
  File "build\assets\items.py", line 137, in get_item_icon
TypeError: argument of type 'NoneType' is not iterable

**Comment by wizzomafizzo** [comment]
can you please upload a copy of the player file you're trying to open. seems to be an issue with the graphics for one of them items. if you haven't already too could you run through the help section on the wiki and reset all of starcheats settings and database

**Comment by SquishyMcDoodles** [comment]
Well I would but the thing is that it crashes on ALL characters. Modded or
not.

**Comment by wizzomafizzo** [comment]
did you run through the reset of all the starcheat settings too? just gotta double check it's not just starcheat messing up itself. and this is for starbound stable right not unstable?

**Comment by SquishyMcDoodles** [comment]
I did manage to fix it by uninstalling and reinstalling starbound

**Comment by wizzomafizzo** [comment]
Glad to hear you got it working again. I will probably keep this open, there may be some underlying reason it happened in the first place which can be fixed.
