### ISSUE TITLE
Starcheat continuous crashing and preventing game start up?

### ISSUE THREAD

**Issue by OrdainedCptn** [wizzomafizzo/starcheat#283]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 558, in open_file
  File "build\gui\mainwindow.py", line 222, in update
  File "build\gui\mainwindow.py", line 830, in update_stat
  File "build\saves.py", line 544, in get_health
KeyError: 'resourceValues'

that's the actual starcheat error message then when i try to start up starbound i get

Fatal Exception caught: (StarException) An error occured during loading: (ItemException) Could not create blueprint item from recipe
Caused by: (ItemException) No such item 'floriantier5chest'

please help

**Comment by medeor413** [comment]
What version of Starcheat and Starbound are you using, and are you using any mods?

**Comment by OrdainedCptn** [comment]
I havent played in a while but i remember using the mod that gives you an extended ship but other than that not that im aware of. im also using the most recent versions of both starcheat and starbound i believe
