### ISSUE TITLE
Starcheat crashing on launch.

### ISSUE THREAD

**Issue by skulltraill** [wizzomafizzo/starcheat#285]
Just installed starbound + starcheat today.

Glad Giraffe + 0.27.1

VC 2010 Redist is installed on my system

I have no mods

Log:
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 154, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 127, in find_assets
  File "build\assets\core.py", line 156, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

**Comment by medeor413** [comment]
As of yesterday, Starbound has updated to Cheerful Giraffe. Starcheat has not yet been updated to work with it yet.

**Comment by skulltraill** [comment]
Aw damn, sorry! My mistake.

**Comment by chrmoritz** [comment]
Starbound 1.0 support is tracked in #282 (with a first nightly build already available).
