### ISSUE TITLE
[1.0 build] Crashes

### ISSUE THREAD

**Issue by Septicity** [wizzomafizzo/starcheat#289]
Heya. In the latest (so far) build of starcheat, it's crashing, of course.
you know the drill.

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 175, in __init__
  File "build\gui\mainwindow.py", line 543, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 119, in get_players
  File "build\gui\openplayer.py", line 136, in populate
  File "build\saves.py", line 617, in get_play_time
KeyError: 'log'

**Comment by medeor413** [comment]
You're attempting to use an older player file with the 1.0 build of Starcheat. Starcheat does not port old characters to 1.0.

**Comment by Septicity** [comment]
actually, it crashed before it could even load a player list.

**Comment by wizzomafizzo** [comment]
@medeor413 this is happening in the initial open player dialog like @Septicity says. i generally just catch these, make a log entry and ignore them from the list

**Comment by medeor413** [comment]
I'll add in a catch for that if you want me to.

**Comment by wizzomafizzo** [comment]
go for your life!

**Comment by medeor413** [comment]
Caught in 9337b9d2eaead720c4cb3bb657381e05cf49d837
