### ISSUE TITLE
Can't Launch Starcheat

### ISSUE THREAD

**Issue by DragonZard** [wizzomafizzo/starcheat#290]
Not sure why it's saying this.

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 158, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 127, in find_assets
  File "build\assets\core.py", line 156, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

**Comment by medeor413** [comment]
You're trying to use the pre-1.0 version of Starcheat on 1.0. Get the 1.0 beta build [here.](https://ci.appveyor.com/api/buildjobs/vhyyfw80v0g157f5/artifacts/dist/starcheat-d44164e-win64.zip)

**Comment by chrmoritz** [comment]
Starbound 1.0 support is tracked here: https://github.com/wizzomafizzo/starcheat/issues/282
The latest nightly build with experimental support for it is available here: https://ci.appveyor.com/project/wizzomafizzo/starcheat/build/master-b62/job/b9swv641yasipudo/artifacts
