### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by maddozz** [wizzomafizzo/starcheat#293]
First it says that the Starbound assests have changed and asks me to rebuild the index.
once i say yes it crashes and i get this error message. i have looked at the other issues but none of the sollutions work.
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 154, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 127, in find_assets
  File "build\assets\core.py", line 156, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

**Comment by medeor413** [comment]
You're trying to use the pre-1.0 build of Starcheat on Starbound 1.0. Get the 1.0 beta build [here.](https://ci.appveyor.com/api/buildjobs/umt2qe3mxck4a9l5/artifacts/dist/starcheat-b30271c-win64.zip)

**Comment by maddozz** [comment]
Aight, thanks
