### ISSUE TITLE
Help...

### ISSUE THREAD

**Issue by Goop69** [wizzomafizzo/starcheat#298]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 175, in __init__
  File "build\gui\mainwindow.py", line 554, in open_file
  File "build\gui\mainwindow.py", line 260, in update
  File "build\gui\mainwindow.py", line 718, in update_bag
  File "build\gui\common.py", line 116, in __init__
  File "build\gui\common.py", line 63, in inv_icon
  File "build\assets\items.py", line 141, in get_item_icon
AttributeError: 'list' object has no attribute 'split'

**Comment by kurisubrooks** [comment]
You're running an outdated version of Starcheat. Please download the latest nightly build [here](https://ci.appveyor.com/api/buildjobs/akpjc262ak1jq0fn/artifacts/dist/starcheat-8a1100b-win64.zip) to fix this issue. Please close this issue.

**Comment by Goop69** [comment]
I have the latest version of Starcheat, and I only can run 1 character.

**Comment by kurisubrooks** [comment]
Where did you download the "latest version" from? 
The current latest version on GitHub does not support Starbound 1.0. 
The latest download link posted in #288 is also out of date.

**Comment by Goop69** [comment]
It's a nightly build

**Comment by kurisubrooks** [comment]
Can I please have the exact version number?

**Comment by Goop69** [comment]
let me check.

**Comment by Goop69** [comment]
starcheat-72bb13e-win64

**Comment by kurisubrooks** [comment]
As I said above, you are running an outdated version of Starcheat. This bug has already been fixed in a newer build. Please download the latest build. https://ci.appveyor.com/api/buildjobs/b9swv641yasipudo/artifacts/dist/starcheat-a00f400-win64.zip

**Comment by Goop69** [comment]
Sure.

**Comment by Goop69** [comment]
Thanks dude.
