### ISSUE TITLE
Crash when rebuilding Starbound asset index

### ISSUE THREAD

**Issue by Raesmal** [wizzomafizzo/starcheat#300]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 153, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 142, in find_assets
  File "build\assets\core.py", line 149, in scan_modpak
  File "build\assets\sb_asset.py", line 23, in get_pak_info
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 47: invalid start byte

I am getting this crash when I am prompted to rebuild Starbound asset index on startup. As soon as I accept, it crashes with this same error. I am using the latest version of Starbound (1.0) and I have used various Starcheat versions (b58-b62) and all of them produce the same error. It might be a mod conflict but I would not know which one.

**Comment by jifaxu** [comment]
I have the same problem

**Comment by medeor413** [comment]
This issue is caused by one of the mods you're using. Remove your mods and try again.

**Comment by chrmoritz** [comment]
Can you please list the mods you are using?
Could you please provide the log file following this guide: https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs
Does the game works normally with all of these mods (To test this proper you would need to spawn every stuff from the mods at least once to make sure the game loads every asset of them at least once through.)?

**Comment by Raesmal** [comment]
Certainly. The mods I'm using are...
Glitch Armor Edits
Ceiling Mounted Sprinkler
Instant Crafting
Matter Manipulator Manipulator
Extra Zoom Levels
The Orcana
Item Frame
Extended Songbook
Undertale Music Pack
Frackin' Races
Improved Containers
Xbawks Character Extender
Ground-Penetrating Radar Station
Frackin' Universe (This one is important, for it is the biggest mod and adds the most items.)
XS Mechs - Vehicle Edition

I have tested these mods as workshop mods and even pulled the content packs out and played them with the old fashioned way to mod Starbound. As for the logs, checking in the folder has turned up nothing. There are no logs in the folder. I have launched Starcheat several times and it never generated a log file. 
![log file](https://cloud.githubusercontent.com/assets/20725404/17274730/5973bcb6-56bd-11e6-942b-967ece474ee7.JPG)

I am currently working on spawning every item from all of my mods.

**Comment by Raesmal** [comment]
I have crafted everything from all of the crafting tables that you can obtain in both vanilla and my mods, and I have no errors. It should be nearly all of the items as far as I can tell, though there might be obscure mob drops that I am missing.

**Comment by wizzomafizzo** [comment]
totally unrelated but is there a mod to reduce fall damage?

**Comment by kurisubrooks** [comment]
You could probably customise some clothes in Starcheat to do this.
