### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by spoon2soup** [wizzomafizzo/starcheat#301]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 154, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 127, in find_assets
  File "build\assets\core.py", line 156, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

This is with a fresh install of starbound and happens when I launch star cheat, I have no mods

**Comment by kurisubrooks** [comment]
This looks to me like you're using an outdated version of Starbound, but
you mention it's a clean install. Interesting. I'll get another developer
to take a look.

**Comment by medeor413** [comment]
Clean install of Starbound, i.e. 1.0. This is just another case of wrong Starcheat version.

**Comment by chrmoritz** [comment]
Starbound 1.0 support is tracked here: https://github.com/wizzomafizzo/starcheat/issues/282
The latest nightly build with experimental support for it is available here: https://ci.appveyor.com/project/wizzomafizzo/starcheat/build/master-b62/job/b9swv641yasipudo/artifacts
