### ISSUE TITLE
Starcheat crashes upon opening whether I update assets or not

### ISSUE THREAD

**Issue by bnessie** [wizzomafizzo/starcheat#302]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 154, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 127, in find_assets
  File "build\assets\core.py", line 156, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

**Comment by medeor413** [comment]
You're using a pre-1.0 version of Starcheat with Starbound 1.0. Get the latest build [here](https://ci.appveyor.com/api/buildjobs/hw24l16eni6wdr65/artifacts/dist/starcheat-8a9fde9-win64.zip).

**Comment by bnessie** [comment]
Thank you very much, worked a treat.

**Comment by chrmoritz** [comment]
Starbound 1.0 support is tracked here: #282 btw.
