### ISSUE TITLE
Crash on selecting starbound location

### ISSUE THREAD

**Issue by Fincap** [wizzomafizzo/starcheat#303]
* starcheat version: *0.27.1*
* starbound version and branch: *Stable 1.0.3)*
* the error message your a getting if any:
```
2016-07-31 14:12:48,953 INFO     starcheat init
2016-07-31 14:12:48,953 INFO     Version: 0.27.1 (Glad Giraffe)
2016-07-31 14:12:48,954 INFO     Platform: Windows
2016-07-31 14:12:48,954 INFO     Checking for updates
2016-07-31 14:12:49,348 INFO     Main window init
2016-07-31 14:12:49,350 DEBUG    Setting up wieldable bag
2016-07-31 14:12:49,352 DEBUG    Setting up head bag
2016-07-31 14:12:49,353 DEBUG    Setting up chest bag
2016-07-31 14:12:49,355 DEBUG    Setting up legs bag
2016-07-31 14:12:49,357 DEBUG    Setting up back bag
2016-07-31 14:12:49,358 DEBUG    Setting up main_bag bag
2016-07-31 14:12:49,363 DEBUG    Setting up action_bar bag
2016-07-31 14:12:49,365 DEBUG    Setting up object_bag bag
2016-07-31 14:12:49,369 DEBUG    Setting up tile_bag bag
2016-07-31 14:12:49,370 DEBUG    Setting up essentials bag
2016-07-31 14:12:49,372 DEBUG    Setting up mouse bag
2016-07-31 14:12:49,379 DEBUG    Showing main window
2016-07-31 14:12:49,532 INFO     First setup dialog
2016-07-31 14:13:02,018 INFO     Scanning vanilla assets
2016-07-31 14:13:02,035 DEBUG    Traceback (most recent call last):

2016-07-31 14:13:02,035 DEBUG      File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>

2016-07-31 14:13:02,035 DEBUG      File "build\starcheat.py", line 83, in <module>

2016-07-31 14:13:02,036 DEBUG      File "build\starcheat.py", line 80, in main

2016-07-31 14:13:02,036 DEBUG      File "build\gui\mainwindow.py", line 148, in __init__

2016-07-31 14:13:02,036 DEBUG      File "build\gui\utils.py", line 197, in new_setup_dialog

2016-07-31 14:13:02,036 DEBUG      File "build\gui\utils.py", line 64, in build_assets_db

2016-07-31 14:13:02,036 DEBUG      File "build\assets\core.py", line 127, in find_assets

2016-07-31 14:13:02,036 DEBUG      File "build\assets\core.py", line 156, in scan_asset_folder

2016-07-31 14:13:02,037 DEBUG      File "build\starbound\helpers.py", line 213, in open

2016-07-31 14:13:02,037 DEBUG      File "build\starbound\helpers.py", line 220, in read_stream

2016-07-31 14:13:02,037 DEBUG      File "build\starbound\btreedb4.py", line 119, in initialize

2016-07-31 14:13:02,037 DEBUG      File "build\starbound\sbbf02.py", line 89, in initialize

2016-07-31 14:13:02,037 DEBUG    AssertionError: Invalid file format

2016-07-31 14:13:02,038 DEBUG    Starbound folder: D:\SteamLibrary\SteamApps\common\Starbound
2016-07-31 14:13:02,039 DEBUG    Assets folder: D:\SteamLibrary\SteamApps\common\Starbound\assets
2016-07-31 14:13:02,040 DEBUG    Player folder: D:\SteamLibrary\SteamApps\common\Starbound\giraffe_storage\player
2016-07-31 14:13:16,757 INFO     starcheat init
2016-07-31 14:13:16,757 INFO     Version: 0.27.1 (Glad Giraffe)
2016-07-31 14:13:16,757 INFO     Platform: Windows
2016-07-31 14:13:16,758 INFO     Checking for updates
2016-07-31 14:13:17,175 INFO     Main window init
2016-07-31 14:13:17,175 DEBUG    Setting up wieldable bag
2016-07-31 14:13:17,177 DEBUG    Setting up head bag
2016-07-31 14:13:17,179 DEBUG    Setting up chest bag
2016-07-31 14:13:17,182 DEBUG    Setting up legs bag
2016-07-31 14:13:17,184 DEBUG    Setting up back bag
2016-07-31 14:13:17,185 DEBUG    Setting up main_bag bag
2016-07-31 14:13:17,190 DEBUG    Setting up action_bar bag
2016-07-31 14:13:17,193 DEBUG    Setting up object_bag bag
2016-07-31 14:13:17,198 DEBUG    Setting up tile_bag bag
2016-07-31 14:13:17,200 DEBUG    Setting up essentials bag
2016-07-31 14:13:17,200 DEBUG    Setting up mouse bag
2016-07-31 14:13:17,208 DEBUG    Showing main window
2016-07-31 14:13:17,344 INFO     First setup dialog
2016-07-31 14:13:17,346 INFO     Starbound folder: D:\SteamLibrary\SteamApps\common\Starbound
2016-07-31 14:13:17,346 INFO     Checking assets hash
2016-07-31 14:13:17,347 INFO     Hashes don't match, updating index
2016-07-31 14:13:20,962 INFO     Scanning vanilla assets
2016-07-31 14:13:20,965 DEBUG    Traceback (most recent call last):

2016-07-31 14:13:20,966 DEBUG      File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>

2016-07-31 14:13:20,966 DEBUG      File "build\starcheat.py", line 83, in <module>

2016-07-31 14:13:20,967 DEBUG      File "build\starcheat.py", line 80, in main

2016-07-31 14:13:20,967 DEBUG      File "build\gui\mainwindow.py", line 154, in __init__

2016-07-31 14:13:20,967 DEBUG      File "build\gui\utils.py", line 103, in check_index_valid

2016-07-31 14:13:20,968 DEBUG      File "build\gui\utils.py", line 64, in build_assets_db

2016-07-31 14:13:20,968 DEBUG      File "build\assets\core.py", line 127, in find_assets

2016-07-31 14:13:20,968 DEBUG      File "build\assets\core.py", line 156, in scan_asset_folder

2016-07-31 14:13:20,969 DEBUG      File "build\starbound\helpers.py", line 213, in open

2016-07-31 14:13:20,969 DEBUG      File "build\starbound\helpers.py", line 220, in read_stream

2016-07-31 14:13:20,969 DEBUG      File "build\starbound\btreedb4.py", line 119, in initialize

2016-07-31 14:13:20,970 DEBUG      File "build\starbound\sbbf02.py", line 89, in initialize

2016-07-31 14:13:20,970 DEBUG    AssertionError: Invalid file format

2016-07-31 14:13:20,971 DEBUG    Starbound folder: D:\SteamLibrary\SteamApps\common\Starbound
2016-07-31 14:13:20,973 DEBUG    Assets folder: D:\SteamLibrary\SteamApps\common\Starbound\assets
2016-07-31 14:13:20,975 DEBUG    Player folder: D:\SteamLibrary\SteamApps\common\Starbound\giraffe_storage\player
2016-07-31 14:14:08,089 INFO     starcheat init
2016-07-31 14:14:08,089 INFO     Version: 0.27.1 (Glad Giraffe)
2016-07-31 14:14:08,089 INFO     Platform: Windows
2016-07-31 14:14:08,090 INFO     Checking for updates
2016-07-31 14:14:08,479 INFO     Main window init
2016-07-31 14:14:08,480 DEBUG    Setting up wieldable bag
2016-07-31 14:14:08,481 DEBUG    Setting up head bag
2016-07-31 14:14:08,483 DEBUG    Setting up chest bag
2016-07-31 14:14:08,483 DEBUG    Setting up legs bag
2016-07-31 14:14:08,485 DEBUG    Setting up back bag
2016-07-31 14:14:08,485 DEBUG    Setting up main_bag bag
2016-07-31 14:14:08,490 DEBUG    Setting up action_bar bag
2016-07-31 14:14:08,492 DEBUG    Setting up object_bag bag
2016-07-31 14:14:08,498 DEBUG    Setting up tile_bag bag
2016-07-31 14:14:08,500 DEBUG    Setting up essentials bag
2016-07-31 14:14:08,500 DEBUG    Setting up mouse bag
2016-07-31 14:14:08,502 DEBUG    Showing main window
2016-07-31 14:14:08,669 INFO     First setup dialog
2016-07-31 14:14:59,228 INFO     Scanning vanilla assets
2016-07-31 14:14:59,229 DEBUG    Traceback (most recent call last):

2016-07-31 14:14:59,229 DEBUG      File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>

2016-07-31 14:14:59,230 DEBUG      File "build\starcheat.py", line 83, in <module>

2016-07-31 14:14:59,230 DEBUG      File "build\starcheat.py", line 80, in main

2016-07-31 14:14:59,230 DEBUG      File "build\gui\mainwindow.py", line 148, in __init__

2016-07-31 14:14:59,230 DEBUG      File "build\gui\utils.py", line 197, in new_setup_dialog

2016-07-31 14:14:59,230 DEBUG      File "build\gui\utils.py", line 64, in build_assets_db

2016-07-31 14:14:59,230 DEBUG      File "build\assets\core.py", line 127, in find_assets

2016-07-31 14:14:59,230 DEBUG      File "build\assets\core.py", line 156, in scan_asset_folder

2016-07-31 14:14:59,231 DEBUG      File "build\starbound\helpers.py", line 213, in open

2016-07-31 14:14:59,231 DEBUG      File "build\starbound\helpers.py", line 220, in read_stream

2016-07-31 14:14:59,231 DEBUG      File "build\starbound\btreedb4.py", line 119, in initialize

2016-07-31 14:14:59,231 DEBUG      File "build\starbound\sbbf02.py", line 89, in initialize

2016-07-31 14:14:59,231 DEBUG    AssertionError: Invalid file format

2016-07-31 14:14:59,232 DEBUG    Starbound folder: D:\SteamLibrary\SteamApps\common\Starbound
2016-07-31 14:14:59,233 DEBUG    Assets folder: D:\SteamLibrary\SteamApps\common\Starbound\assets
2016-07-31 14:14:59,233 DEBUG    Player folder: D:\SteamLibrary\SteamApps\common\Starbound\giraffe_storage\player

```

Basically, I'm trying to start it up for the first time. It's telling me to navigate to my Starbound installation location, but it gives me that error message when I select the folder.

**Comment by medeor413** [comment]
You're using the pre-1.0 version of Starcheat with Starbound 1.0. Please grab the 1.0 build [here.](https://ci.appveyor.com/api/buildjobs/47g6sl5ymalkj00u/artifacts/dist/starcheat-39219c2-win64.zip)
@chrmoritz, can you add, like, a giant red label to the 0.27.1 release that says it's incompatible with Starbound 1.0?

**Comment by chrmoritz** [comment]
Starbound 1.0 support is tracked here: #282
The latest nightly build with experimental support for it is available here: https://ci.appveyor.com/project/wizzomafizzo/starcheat/build/master-b64/job/47g6sl5ymalkj00u/artifacts

@medeor413 It's already there except it being red, which is not possible with markdown. People just have to start learning to read ...

**Comment by kurisubrooks** [comment]
GitHub markdown accepts HTML and inline CSS in READMEs. It's totally
possible.

**Comment by chrmoritz** [comment]
@kurisubrooks I've tested `<span style="color: red;">test</span>` and it didn't worked on the release page. But maybe we should add a notice to the readme and the issue template too.

**Comment by kurisubrooks** [comment]
I'm not sure if it would work on the Releases page, but I know HTML is
accepted for markdown files in the repo. Maybe put a h1 size warning on
both the readme and releases page.
