### ISSUE TITLE
Updating item slots crash

### ISSUE THREAD

**Issue by Spectatroll** [wizzomafizzo/starcheat#305]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 175, in __init__
  File "build\gui\mainwindow.py", line 552, in open_file
  File "build\gui\mainwindow.py", line 258, in update
  File "build\gui\mainwindow.py", line 716, in update_bag
  File "build\gui\common.py", line 116, in __init__
  File "build\gui\common.py", line 63, in inv_icon
  File "build\assets\items.py", line 141, in get_item_icon
AttributeError: 'list' object has no attribute 'split'

using latest build starcheat(29aacb5-win64)

**Comment by kurisubrooks** [comment]
Your build is out of date. Please update to `39219c2-win64` here: https://ci.appveyor.com/api/buildjobs/47g6sl5ymalkj00u/artifacts/dist/starcheat-39219c2-win64.zip

Because this bug was already fixed in newer versions, please close this pull request.

**Comment by kurisubrooks** [comment]
Just out of curiosity, where did you get the link to that download? Everyone we've encountered in the issues seems to be having it. Has someone posted this **outdated** link somewhere online? Reddit perhaps? @Spectatroll

**Comment by Spectatroll** [comment]
my bad... i don't check the version history.. btw i got it from @medeor413 reply here
https://github.com/wizzomafizzo/starcheat/issues/292
