### ISSUE TITLE
I Can't Figure this out. It Crashes on Launch(StarCheat)

### ISSUE THREAD

**Issue by ImVertex** [wizzomafizzo/starcheat#308]
Here is the Details,
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 154, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 127, in find_assets
  File "build\assets\core.py", line 156, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

**Comment by kurisubrooks** [comment]
Starcheat 0.27 is incompatible with Starbound 1.0.
Starcheat 1.0 builds will be available some time in the near future.

**Comment by kurisubrooks** [comment]
@chrmoritz you can close this one.
