### ISSUE TITLE
Starcheat crash 

### ISSUE THREAD

**Issue by Xeveph** [wizzomafizzo/starcheat#310]
* starcheat version: 27.1
* starbound version and branch (stable / unstable / nightly): Nightly #288
* the error message your a getting if any:
Oops. starcheat has crashed
Insert error message from the details field of the error dialog here
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 148, in __init__
  File "build\gui\utils.py", line 197, in new_setup_dialog
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 127, in find_assets
  File "build\assets\core.py", line 156, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

Logs:
2016-10-18 00:50:39,128 INFO     starcheat init
2016-10-18 00:50:39,128 INFO     Version: 0.27.1 (Glad Giraffe)
2016-10-18 00:50:39,128 INFO     Platform: Windows
2016-10-18 00:50:39,129 INFO     Checking for updates
2016-10-18 00:50:39,663 INFO     Main window init
2016-10-18 00:50:39,664 DEBUG    Setting up wieldable bag
2016-10-18 00:50:39,666 DEBUG    Setting up head bag
2016-10-18 00:50:39,667 DEBUG    Setting up chest bag
2016-10-18 00:50:39,670 DEBUG    Setting up legs bag
2016-10-18 00:50:39,673 DEBUG    Setting up back bag
2016-10-18 00:50:39,674 DEBUG    Setting up main_bag bag
2016-10-18 00:50:39,684 DEBUG    Setting up action_bar bag
2016-10-18 00:50:39,685 DEBUG    Setting up object_bag bag
2016-10-18 00:50:39,687 DEBUG    Setting up tile_bag bag
2016-10-18 00:50:39,693 DEBUG    Setting up essentials bag
2016-10-18 00:50:39,696 DEBUG    Setting up mouse bag
2016-10-18 00:50:39,699 DEBUG    Showing main window
2016-10-18 00:50:39,897 INFO     First setup dialog
2016-10-18 00:50:51,679 INFO     Scanning vanilla assets
2016-10-18 00:50:51,680 DEBUG    Traceback (most recent call last):

2016-10-18 00:50:51,680 DEBUG      File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>

2016-10-18 00:50:51,680 DEBUG      File "build\starcheat.py", line 86, in <module>

2016-10-18 00:50:51,680 DEBUG      File "build\starcheat.py", line 83, in main

2016-10-18 00:50:51,680 DEBUG      File "build\gui\mainwindow.py", line 148, in __init__

2016-10-18 00:50:51,680 DEBUG      File "build\gui\utils.py", line 197, in new_setup_dialog

2016-10-18 00:50:51,680 DEBUG      File "build\gui\utils.py", line 64, in build_assets_db

2016-10-18 00:50:51,681 DEBUG      File "build\assets\core.py", line 127, in find_assets

2016-10-18 00:50:51,681 DEBUG      File "build\assets\core.py", line 156, in scan_asset_folder

2016-10-18 00:50:51,681 DEBUG      File "build\starbound\helpers.py", line 213, in open

2016-10-18 00:50:51,681 DEBUG      File "build\starbound\helpers.py", line 220, in read_stream

2016-10-18 00:50:51,681 DEBUG      File "build\starbound\btreedb4.py", line 119, in initialize

2016-10-18 00:50:51,681 DEBUG      File "build\starbound\sbbf02.py", line 89, in initialize

2016-10-18 00:50:51,681 DEBUG    AssertionError: Invalid file format

2016-10-18 00:50:51,682 DEBUG    Starbound folder: E:\SteamLibrary\steamapps\common\Starbound
2016-10-18 00:50:51,682 DEBUG    Assets folder: E:\SteamLibrary\steamapps\common\Starbound\assets
2016-10-18 00:50:51,683 DEBUG    Player folder: E:\SteamLibrary\steamapps\common\Starbound\giraffe_storage\player

**Comment by medeor413** [comment]
You're using the pre-1.0 build of Starcheat with Starbound 1.x. Please grab the 1.x Starcheat build [here.](https://ci.appveyor.com/api/buildjobs/mj9h9ri0cxdgfabc/artifacts/dist%2Fstarcheat-9d543cd-win64.zip)
