### ISSUE TITLE
Starcheat crash during startup. SBBF02 Invalid file format.

### ISSUE THREAD

**Issue by majorendian** [wizzomafizzo/starcheat#312]
Hello, I'd like to report a crash in case you are still working on this.

This is the output:
```
INFO     starcheat init
INFO     Version: 0.27.1 (Glad Giraffe)
INFO     Platform: Linux
INFO     Checking for updates
INFO     Main window init
INFO     First setup dialog
INFO     Scanning vanilla assets
Traceback (most recent call last):
  File "./build/starcheat.py", line 83, in <module>
    main()
  File "./build/starcheat.py", line 80, in main
    gui.mainwindow.MainWindow()
  File "/home/tino/Lab/Starcheat/build/gui/mainwindow.py", line 148, in __init__
    if not new_setup_dialog(self.window):
  File "/home/tino/Lab/Starcheat/build/gui/utils.py", line 197, in new_setup_dialog
    if not build_assets_db(parent):
  File "/home/tino/Lab/Starcheat/build/gui/utils.py", line 64, in build_assets_db
    asset_files = assets_db.find_assets()
  File "/home/tino/Lab/Starcheat/build/assets/core.py", line 127, in find_assets
    vanilla_assets = self.scan_asset_folder(vanilla_path)
  File "/home/tino/Lab/Starcheat/build/assets/core.py", line 156, in scan_asset_folder
    db = starbound.open_file(pak_path)
  File "/home/tino/Lab/Starcheat/build/starbound/helpers.py", line 213, in open
    return read_stream(builtins.open(path, 'rb'), extension)
  File "/home/tino/Lab/Starcheat/build/starbound/helpers.py", line 220, in read_stream
    file.initialize()
  File "/home/tino/Lab/Starcheat/build/starbound/btreedb4.py", line 119, in initialize
    super(FileBTreeDB4, self).initialize()
  File "/home/tino/Lab/Starcheat/build/starbound/sbbf02.py", line 89, in initialize
    assert stream.read(6) in (b'SBBF02', b'SBBF03'), 'Invalid file format'
AssertionError: Invalid file format
```

And this is `hexdump -C packed.pak`
```
00000000  53 42 41 73 73 65 74 36  00 00 00 00 30 47 5f 08  |SBAsset6....0G_.|
00000010  7b 0a 20 20 22 61 69 41  6e 69 6d 61 74 69 6f 6e  |{.  "aiAnimation|
00000020  73 22 20 3a 20 7b 0a 20  20 20 20 22 69 64 6c 65  |s" : {.    "idle|
00000030  22 20 3a 20 7b 0a 20 20  20 20 20 20 22 66 72 61  |" : {.      "fra|
00000040  6d 65 73 22 20 3a 20 22  3c 69 6d 61 67 65 3e 3a  |mes" : "<image>:|
```

I tried uninstalling all mods, including deleting all my players. Even tried this on the Starbound - Unstable where I have touched nothing.
But it still crashes on this same error message.
I tried using the 0.17 version as it was suggested but it does exactly the same thing. Any suggestion would be deeply appreciated.

I am using starbound version 1.1.1

**Comment by medeor413** [comment]
You're using the pre-1.x version of Starcheat with a 1.x version of Starbound. Please download [my fork](https://github.com/medeor413/starcheat) and use that instead.

**Comment by majorendian** [comment]
alright, thanks I'll try that

**Comment by majorendian** [comment]
That solved the problem. Thanks again.
