### ISSUE TITLE
Crashing after first launch

### ISSUE THREAD

**Issue by muk4a** [wizzomafizzo/starcheat#313]
## Issue details:

* starcheat version: *9d543cd*
* starbound version and branch (stable / unstable / nightly):  *nightly*
* the error message your a getting if any:
```
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 179, in __init__
  File "build\gui\mainwindow.py", line 556, in open_file
  File "build\gui\mainwindow.py", line 206, in update
  File "build\saves.py", line 565, in get_pixels
KeyError: 'money'

Succesfully started starcheat,then played a while and every time i try to load a player it crashes

**Comment by medeor413** [comment]
Ah, wonderful, looks like player files were changed some in Nightly. I'll push a fix when 1.2 gets a stable release.

**Comment by medeor413** [comment]
Alright, we now have a build ready for 1.2 [here.](https://ci.appveyor.com/api/buildjobs/ve8yig7de3sqf89c/artifacts/dist%2Fstarcheat-e9aeb3c-win64.zip)

**Comment by 0Zero-00** [comment]
That's been taken down, it seems...

**Comment by chrmoritz** [comment]
Yeah, appveyor doesn’t store release artifacts indefinitely anymore. But I’ve uploaded a backup to our releases page as a pre release here: https://github.com/wizzomafizzo/starcheat/releases/tag/beta-v1

**Comment by 0Zero-00** [comment]
I tried the link there, still nothing. 

Error report:
```
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 157, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 52, in build_assets_db
  File "build\assets\core.py", line 53, in __init__
sqlite3.OperationalError: unable to open database file
```

**Comment by chrmoritz** [comment]
Have to tried deleting the database, as I've told you in https://github.com/wizzomafizzo/starcheat/issues/359#issuecomment-421324089?
