### ISSUE TITLE
Starcheat Has Crashed Error

### ISSUE THREAD

**Issue by Dantomo** [wizzomafizzo/starcheat#314]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 179, in __init__
  File "build\gui\mainwindow.py", line 556, in open_file
  File "build\gui\mainwindow.py", line 206, in update
  File "build\saves.py", line 565, in get_pixels
KeyError: 'money'

**Comment by Fendotl** [comment]
Not to be rude or anything but when will there be a new update?

**Comment by medeor413** [comment]
Alright, we have 1.2 builds ready now, you can download it [here.](https://ci.appveyor.com/api/buildjobs/ve8yig7de3sqf89c/artifacts/dist%2Fstarcheat-e9aeb3c-win64.zip)
