### ISSUE TITLE
New asset crash

### ISSUE THREAD

**Issue by gijoe2cool** [wizzomafizzo/starcheat#316]
Ok, I hope I'm not just posting old stuff here, but... I just put starcheat on here, so I am pretty sure I'm using the latest version, and I believe it's a nightly. But it tells me that the assests have changed, and do I want to update, so I hit yes, then it crashes, and if I hit no, it crashes, and appears to be the same error log no matter what, and it said copy and paste, and I did, so here it is.

Traceback (most recent call last):
  File "./build/starcheat.py", line 83, in <module>
    main()
  File "./build/starcheat.py", line 80, in main
    gui.mainwindow.MainWindow()
  File "/home/gijoe2cool/starcheat/build/gui/mainwindow.py", line 154, in __init__
    if not check_index_valid(self.window):
  File "/home/gijoe2cool/starcheat/build/gui/utils.py", line 103, in check_index_valid
    return build_assets_db(parent)
  File "/home/gijoe2cool/starcheat/build/gui/utils.py", line 64, in build_assets_db
    asset_files = assets_db.find_assets()
  File "/home/gijoe2cool/starcheat/build/assets/core.py", line 127, in find_assets
    vanilla_assets = self.scan_asset_folder(vanilla_path)
  File "/home/gijoe2cool/starcheat/build/assets/core.py", line 156, in scan_asset_folder
    db = starbound.open_file(pak_path)
  File "/home/gijoe2cool/starcheat/build/starbound/helpers.py", line 213, in open
    return read_stream(builtins.open(path, 'rb'), extension)
  File "/home/gijoe2cool/starcheat/build/starbound/helpers.py", line 220, in read_stream
    file.initialize()
  File "/home/gijoe2cool/starcheat/build/starbound/btreedb4.py", line 119, in initialize
    super(FileBTreeDB4, self).initialize()
  File "/home/gijoe2cool/starcheat/build/starbound/sbbf02.py", line 89, in initialize
    assert stream.read(6) in (b'SBBF02', b'SBBF03'), 'Invalid file format'
AssertionError: Invalid file format

I looked at some of the other crash reports, but none of them seemed to apply to me since you were only handing out .xip files for windows, and I have a source build for linux...

Also, I'm in no rush to play, so no huge rush getting back to me, and if all you can tell me "sorry, can't do linux yet" i'm fine with that too. lol.

**Comment by chrmoritz** [comment]
You have Tor Build #288 for latest Starbound Version support.

**Comment by gijoe2cool** [comment]
How do I know which build I have, cause I literally just built it, with what I thought was the latest build, no more than 10 mins ago.

**Comment by chrmoritz** [comment]
The error indicates that you have just build master and not that pull request. Try to build this: https://github.com/wizzomafizzo/starcheat/archive/4994d3f.tar.gz

**Comment by gijoe2cool** [comment]
Ok, I will attempt to build. Thank you.
