### ISSUE TITLE
Crash on rebuilding assets

### ISSUE THREAD

**Issue by ShivMcStabby** [wizzomafizzo/starcheat#319]
I launched Starcheat, it asked me if I wanted to rebuild assets. I clicked yes and this appeared

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 153, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 126, in find_assets
  File "build\assets\core.py", line 158, in scan_asset_folder
  File "build\assets\sb_asset.py", line 49, in create_file_index
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 0: invalid continuation byte

I relaunched it, selected no. A sequence of error messages claiming the Starbound directory had changed appeared, I went through them all to finally receive the exact same error message. Anybody has any clues ?

**Comment by DSMTurboAWD** [comment]
Are you on a windows system? Did you compile yourself or did you use the bots? I might just redownload and rebuild and try again

**Comment by ShivMcStabby** [comment]
I'm not sure of what that means. I downloaded the .rar and extracted it to a folder on my desktop.

**Comment by DSMTurboAWD** [comment]
are you downloading from here:
https://ci.appveyor.com/project/wizzomafizzo/starcheat/branch/dev 
 or are you compiling yourself from here:
https://github.com/wizzomafizzo/starcheat/archive/master.zip

**Comment by ShivMcStabby** [comment]
No and no
This might sound dumb, but I don't know how to download from appveyor :/
