### ISSUE TITLE
starcheat has crashed

### ISSUE THREAD

**Issue by koonpeet9880** [wizzomafizzo/starcheat#320]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 164, in __init__
  File "build\assets\core.py", line 275, in species
  File "build\assets\species.py", line 27, in __init__
  File "build\assets\core.py", line 217, in read
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

**Comment by medeor413** [comment]
You're using a pre-1.0 version of Starcheat with a 1.x version of Starbound. Download the latest build with 1.x support [here.](https://ci.appveyor.com/api/buildjobs/ve8yig7de3sqf89c/artifacts/dist%2Fstarcheat-e9aeb3c-win64.zip)
