### ISSUE TITLE
starcheat has crashed

### ISSUE THREAD

**Issue by koonpeet9880** [wizzomafizzo/starcheat#321]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 151, in __init__
  File "build\gui\utils.py", line 197, in new_setup_dialog
  File "build\gui\utils.py", line 86, in build_assets_db
  File "build\gui\utils.py", line 30, in make_pak_hash
  File "build\config.py", line 36, in read
  File "C:\Python34-x64\lib\configparser.py", line 936, in __getitem__
KeyError: 'starcheat'

**Comment by chrmoritz** [comment]
Looks like your starcheat config file got corrupted. Try to reset/delete it following: https://github.com/wizzomafizzo/starcheat/wiki/help#reset-all-settings
