### ISSUE TITLE
Starcheat crashing. Don't know why.

### ISSUE THREAD

**Issue by Kohai524** [wizzomafizzo/starcheat#324]
recently downloaded starcheat again. only problem is that when i open it, and press yes to rebuild the assets index, or even no, it crashes and I get this

Traceback (most recent call last):
  File "/Users/s232501/Desktop/starcheat.app/Contents/Resources/__boot__.py", line 399, in <module>
  File "/Users/s232501/Desktop/starcheat.app/Contents/Resources/__boot__.py", line 336, in _run
  File "/Users/s232501/Desktop/starcheat.app/Contents/Resources/starcheat.py", line 83, in <module>
  File "/Users/s232501/Desktop/starcheat.app/Contents/Resources/starcheat.py", line 80, in main
  File "gui/mainwindow.pyc", line 154, in __init__
  File "gui/utils.pyc", line 103, in check_index_valid
  File "gui/utils.pyc", line 64, in build_assets_db
  File "assets/core.pyc", line 127, in find_assets
  File "assets/core.pyc", line 156, in scan_asset_folder
  File "starbound/helpers.pyc", line 213, in open
  File "starbound/helpers.pyc", line 220, in read_stream
  File "starbound/btreedb4.pyc", line 119, in initialize
  File "starbound/sbbf02.pyc", line 89, in initialize
AssertionError: Invalid file format

If anyone could help, that'd be great.

**Comment by medeor413** [comment]
You're using a pre-1.0 version of Starcheat with a 1.x version of Starbound. Please see the instructions [here](https://github.com/wizzomafizzo/starcheat#install) for building a 1.x version of Starcheat.

**Comment by Kohai524** [comment]
is it possible to do this another way? I cant directly install homebrew because i don't have access to admin on my computer. @medeor413

**Comment by medeor413** [comment]
Unfortunately, I don't use a Mac, so I can't help you there.

**Comment by chrmoritz** [comment]
You shouldn't need admin rights to install homebrew, as one of it advantage is being sodoless.

In theory you could install starcheat outside homebrew after installing all its dependencies, but the official Qt binaries will require admin rights for Installation. So unless you want to spend hours on building it (and it dependencies) from source I highly recommend getting it via homebrew.

**Comment by Kohai524** [comment]
I followed the directions and pasted the line of code into my terminal but when i hit run all it said was that it required administrative rights to run @chrmoritz

**Comment by wizzomafizzo** [comment]
can you get a screenshot of that message?

**Comment by Kohai524** [comment]
![Uploading Screen Shot 2017-02-28 at 1.00.44 PM.png…]()
This is it right here @wizzomafizzo

**Comment by Kohai524** [comment]
oops, didnt mean to close it

**Comment by chrmoritz** [comment]
Looks like you didn't uploaded the screenshot correctly, but I would guess that there is already another homebrew installation owned by another user of this machine in `/user/local`.

What is the output of `whoami && ls -la /usr/local/`?

**Comment by Kohai524** [comment]
instead of a screenshot, i'll copy exactly what it says.

Last login: Wed Mar  1 07:33:38 on ttys000
BHSSL149331:~ s232501$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
This script requires the user s232501 to be an Administrator.
BHSSL149331:~ s232501$ 

and then this is the output of what you wrote.

Last login: Wed Mar  1 07:34:31 on ttys000
BHSSL149331:~ s232501$ whoami && ls -la /usr/local/
s232501
total 0
drwxr-xr-x   6 root  wheel  204 Apr 20  2016 .
drwxr-xr-x@ 12 root  wheel  408 Feb 25  2016 ..
drwxr-xr-x   4 root  wheel  136 Apr 18  2016 bin
drwxr-xr-x   3 root  wheel  102 Apr 18  2016 jamf
drwxr-xr-x  12 root  admin  408 Apr 18  2016 lib
drwxr-xr-x   3 root  wheel  102 Oct 21  2015 share
BHSSL149331:~ s232501$
