### ISSUE TITLE
I don't know what happened...

### ISSUE THREAD

**Issue by SimonTheLemon** [wizzomafizzo/starcheat#325]
This was my crash report:

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 154, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 127, in find_assets
  File "build\assets\core.py", line 156, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

**Comment by medeor413** [comment]
You're using a pre-1.0 version of Starcheat with a 1.x version of Starbound. Download the latest build with 1.x support [here.](https://ci.appveyor.com/api/buildjobs/ve8yig7de3sqf89c/artifacts/dist%2Fstarcheat-e9aeb3c-win64.zip)
