### ISSUE TITLE
Starcheat has crashed (building assets)

### ISSUE THREAD

**Issue by Nanotic** [wizzomafizzo/starcheat#326]
```
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 157, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 52, in build_assets_db
  File "build\assets\core.py", line 53, in __init__
sqlite3.OperationalError: unable to open database file
```

crashes as soon as I start it, using latest starcheat nightly that supports starbound 1.2

This happens when I get prompted to rebuild my assets.
no, I didnt install any new mods. I just re installed windows fresh, and all of a sudden I get this.

**Comment by Nanotic** [comment]
Fixed by deleting my assets.db and starcheat.ini in %appdata%
