### ISSUE TITLE
Starcheat crash upon launch

### ISSUE THREAD

**Issue by ChaoZed** [wizzomafizzo/starcheat#327]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 164, in __init__
  File "build\assets\core.py", line 275, in species
  File "build\assets\species.py", line 27, in __init__
  File "build\assets\core.py", line 217, in read
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

**Comment by ChaoZed** [comment]
FIXED: 
Downloaded Starcheat from appveyor:
https://ci.appveyor.com/project/wizzomafizzo/starcheat/build/job/ve8yig7de3sqf89c/artifacts

**Comment by FanatiG** [comment]
did not help me
