### ISSUE TITLE
Mac Error El Capitan 10.11.6

### ISSUE THREAD

**Issue by Repethen** [wizzomafizzo/starcheat#331]
Hi there, just homebrewed my mac and tried running starcheat for the first time, but I've been presented with the following message (Glad Giraffe 0.27.1):

Traceback (most recent call last):
  File "/usr/local/opt/starcheat/bin/starcheat", line 83, in <module>
    main()
  File "/usr/local/opt/starcheat/bin/starcheat", line 80, in main
    gui.mainwindow.MainWindow()
  File "/usr/local/Cellar/starcheat/0.27.1/libexec/gui/mainwindow.py", line 154, in __init__
    if not check_index_valid(self.window):
  File "/usr/local/Cellar/starcheat/0.27.1/libexec/gui/utils.py", line 103, in check_index_valid
    return build_assets_db(parent)
  File "/usr/local/Cellar/starcheat/0.27.1/libexec/gui/utils.py", line 64, in build_assets_db
    asset_files = assets_db.find_assets()
  File "/usr/local/Cellar/starcheat/0.27.1/libexec/assets/core.py", line 127, in find_assets
    vanilla_assets = self.scan_asset_folder(vanilla_path)
  File "/usr/local/Cellar/starcheat/0.27.1/libexec/assets/core.py", line 156, in scan_asset_folder
    db = starbound.open_file(pak_path)
  File "/usr/local/Cellar/starcheat/0.27.1/libexec/starbound/helpers.py", line 213, in open
    return read_stream(builtins.open(path, 'rb'), extension)
  File "/usr/local/Cellar/starcheat/0.27.1/libexec/starbound/helpers.py", line 220, in read_stream
    file.initialize()
  File "/usr/local/Cellar/starcheat/0.27.1/libexec/starbound/btreedb4.py", line 119, in initialize
    super(FileBTreeDB4, self).initialize()
  File "/usr/local/Cellar/starcheat/0.27.1/libexec/starbound/sbbf02.py", line 89, in initialize
    assert stream.read(6) in (b'SBBF02', b'SBBF03'), 'Invalid file format'
AssertionError: Invalid file format

No idea what has caused this

**Comment by medeor413** [comment]
You're using a pre-1.0 version of Starcheat with a 1.x version of Starbound. Please see the instructions [here](https://github.com/wizzomafizzo/starcheat#install) for building a 1.x version of Starcheat.

**Comment by chrmoritz** [comment]
More precisely you have to run the devel version (with Starbound 1.0) support,w hich you can install with `brew install chrmoritz/starcheat/starcheat --devel`
