### ISSUE TITLE
Opps, starcheat has crashed

### ISSUE THREAD

**Issue by Wafleman** [wizzomafizzo/starcheat#334]
Traceback (most recent call last):
  File "/private/var/folders/9t/3q9jr6dj2s1_cb_tbxk3flk00000gn/T/AppTranslocation/93D64C26-8938-4BB4-8E45-02796778FBEC/d/StarCheat.app/Contents/Resources/__boot__.py", line 399, in <module>
  File "/private/var/folders/9t/3q9jr6dj2s1_cb_tbxk3flk00000gn/T/AppTranslocation/93D64C26-8938-4BB4-8E45-02796778FBEC/d/StarCheat.app/Contents/Resources/__boot__.py", line 336, in _run
  File "/private/var/folders/9t/3q9jr6dj2s1_cb_tbxk3flk00000gn/T/AppTranslocation/93D64C26-8938-4BB4-8E45-02796778FBEC/d/StarCheat.app/Contents/Resources/starcheat.py", line 83, in <module>
  File "/private/var/folders/9t/3q9jr6dj2s1_cb_tbxk3flk00000gn/T/AppTranslocation/93D64C26-8938-4BB4-8E45-02796778FBEC/d/StarCheat.app/Contents/Resources/starcheat.py", line 80, in main
  File "gui/mainwindow.pyc", line 154, in __init__
  File "gui/utils.pyc", line 103, in check_index_valid
  File "gui/utils.pyc", line 64, in build_assets_db
  File "assets/core.pyc", line 127, in find_assets
  File "assets/core.pyc", line 156, in scan_asset_folder
  File "starbound/helpers.pyc", line 213, in open
  File "starbound/helpers.pyc", line 220, in read_stream
  File "starbound/btreedb4.pyc", line 119, in initialize
  File "starbound/sbbf02.pyc", line 89, in initialize
AssertionError: Invalid file format

**Comment by medeor413** [comment]
You're using a pre-1.0 version of Starcheat with a 1.x version of Starbound. Please see the instructions [here](https://github.com/wizzomafizzo/starcheat#install) for building a 1.x version of Starcheat.
