### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Crachfire** [wizzomafizzo/starcheat#338]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 148, in __init__
  File "build\gui\utils.py", line 197, in new_setup_dialog
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 127, in find_assets
  File "build\assets\core.py", line 156, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

## Please follow these steps before opening a new issue:

* [ ] try updating starcheat to the [latest](https://github.com/wizzomafizzo/starcheat/releases/latest) version [compatible](https://github.com/wizzomafizzo/starcheat#downloads) with your Starbound version and retry (maybe your issue is already fixed)
* [ ] search [all open issues](https://github.com/wizzomafizzo/starcheat/issues?utf8=%E2%9C%93&q=is%3Aopen+) for issues similar to yours. If you find a issue matching yours consider commenting in this issue (and providing additional informations there) rather then opening a new one.
* [ ] if you think your issues isn't already reporting please open a new one and try to include as much details as possible describing your issue

## Issue details:
*Please try to fill out as many fields as you can below (by replacing the text between the two *).*

* starcheat version: *insert starcheat version here (e.g. `0.27.1`)*
* starbound version and branch (stable / unstable / nightly): *insert starbound version here (e.g. `Glad Giraffe (stable)` or `nightly`)*
* the error message your a getting if any:
```
Insert error message from the details field of the error dialog here
```
* a link to your starcheat log file: *insert link here (e.g. `https://gist.github.com/Sparksolur/a65ed1e6eda8566b5d86`)*
  * [read this wiki entry](https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs) for a guide how to get the logs
  * upload the log to somewhere, where we can access them (preferable [gist](https://gist.github.com/))
* if the issue is related to a player files please upload the affected player file somewhere if possible: *insert player file here*
* if the issue is related to a mod please link to the mod you are using if possible: *insert mod link here*

**Comment by medeor413** [comment]
You're using a pre-1.0 version of Starcheat with a 1.x version of Starbound. Download the latest build with 1.x support [here.](https://ci.appveyor.com/api/buildjobs/ve8yig7de3sqf89c/artifacts/dist%2Fstarcheat-e9aeb3c-win64.zip)
