### ISSUE TITLE
It gives me false hope

### ISSUE THREAD

**Issue by GideonEra** [wizzomafizzo/starcheat#339]
## Please follow these steps before opening a new issue:

* [ ] try updating starcheat to the [latest](https://github.com/wizzomafizzo/starcheat/releases/latest) version [compatible](https://github.com/wizzomafizzo/starcheat#downloads) with your Starbound version and retry (maybe your issue is already fixed)
* [ ] search [all open issues](https://github.com/wizzomafizzo/starcheat/issues?utf8=%E2%9C%93&q=is%3Aopen+) for issues similar to yours. If you find a issue matching yours consider commenting in this issue (and providing additional informations there) rather then opening a new one.
* [ ] if you think your issues isn't already reporting please open a new one and try to include as much details as possible describing your issue

## Issue details:
I would open starcheat and my characters show up everything is fine until I try and open one of them an boom crash

* starcheat version: `0.27.1`
* starbound version and branch (stable / unstable / nightly): *insert starbound version here (e.g. `Glad Giraffe (stable)` or `nightly`)*
* the error message your a getting if any:
```
Insert error message from the details field of the error dialog here
```
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 175, in __init__
  File "build\gui\mainwindow.py", line 552, in open_file
  File "build\gui\mainwindow.py", line 202, in update
  File "build\saves.py", line 565, in get_pixels
KeyError: 'money'

**Comment by medeor413** [comment]
Looks like you're using a pre-1.2 version of Starcheat with a post-1.2 version of Starbound. Redownload [the latest Starcheat](https://ci.appveyor.com/api/buildjobs/ve8yig7de3sqf89c/artifacts/dist%2Fstarcheat-e9aeb3c-win64.zip) and try again.
