### ISSUE TITLE
Issue for mac

### ISSUE THREAD

**Issue by mapledakii** [wizzomafizzo/starcheat#341]
Traceback (most recent call last):
  File "/private/var/folders/km/gtrn_19n5vb83jp3pn50hxhc0000gn/T/AppTranslocation/848B5CBD-9E2A-4367-81B3-F5CFBC02D83D/d/StarCheat.app/Contents/Resources/__boot__.py", line 399, in <module>
  File "/private/var/folders/km/gtrn_19n5vb83jp3pn50hxhc0000gn/T/AppTranslocation/848B5CBD-9E2A-4367-81B3-F5CFBC02D83D/d/StarCheat.app/Contents/Resources/__boot__.py", line 336, in _run
  File "/private/var/folders/km/gtrn_19n5vb83jp3pn50hxhc0000gn/T/AppTranslocation/848B5CBD-9E2A-4367-81B3-F5CFBC02D83D/d/StarCheat.app/Contents/Resources/starcheat.py", line 83, in <module>
  File "/private/var/folders/km/gtrn_19n5vb83jp3pn50hxhc0000gn/T/AppTranslocation/848B5CBD-9E2A-4367-81B3-F5CFBC02D83D/d/StarCheat.app/Contents/Resources/starcheat.py", line 80, in main
  File "gui/mainwindow.pyc", line 154, in __init__
  File "gui/utils.pyc", line 103, in check_index_valid
  File "gui/utils.pyc", line 64, in build_assets_db
  File "assets/core.pyc", line 127, in find_assets
  File "assets/core.pyc", line 156, in scan_asset_folder
  File "starbound/helpers.pyc", line 213, in open
  File "starbound/helpers.pyc", line 220, in read_stream
  File "starbound/btreedb4.pyc", line 119, in initialize
  File "starbound/sbbf02.pyc", line 89, in initialize
AssertionError: Invalid file format

**Comment by chrmoritz** [comment]
You are using a build of starcheat for Starbound < 1.0 with a Starbound version >= 1.0. Try to build the 1.0 nightly with `brew install chrmoritz/starcheat/starcheat --devel`, see: https://github.com/wizzomafizzo/starcheat#mac-homebrew-head-build.
