### ISSUE TITLE
Oops, Starcheat has Crashed.

### ISSUE THREAD

**Issue by DaveTheDave** [wizzomafizzo/starcheat#343]
*

* starcheat version: *392119c2)*
* starbound version and branch (stable / unstable / nightly): *nightly*
* the error message your a getting if any:
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 179, in __init__
  File "build\gui\mainwindow.py", line 556, in open_file
  File "build\gui\mainwindow.py", line 206, in update
  File "build\saves.py", line 565, in get_pixels
KeyError: 'money'

**Comment by Umbraism** [comment]
I'm getting the same problem, would appreciate if someone can tell me what to do.

**Comment by medeor413** [comment]
Looks like you're using a pre-1.2 version of Starcheat with a post-1.2 version of Starbound. Redownload [the latest Starcheat](https://ci.appveyor.com/api/buildjobs/ve8yig7de3sqf89c/artifacts/dist%2Fstarcheat-e9aeb3c-win64.zip) and try again.
