### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by 1Thurisaz1** [wizzomafizzo/starcheat#353]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 148, in __init__
  File "build\gui\utils.py", line 197, in new_setup_dialog
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 127, in find_assets
  File "build\assets\core.py", line 156, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

**Comment by Levianne** [comment]
Hello, I'm new here, but let's go straight to the point. My Starcheat (I guess it's latest nightly built version, not sure though - the downloaded zip archive has "a00f400" in it's name, kinda hard for me to know if it's the latest or not) threw an error at me by selecting a character. That means, Starcheat won't crash on it's own until I select who I want to edit. The error is as follows:

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 175, in __init__
  File "build\gui\mainwindow.py", line 552, in open_file
  File "build\gui\mainwindow.py", line 202, in update
  File "build\saves.py", line 565, in get_pixels
KeyError: 'money'

The last two lines have something to do with money/Pixels. Is Starbound currency somehow changed between latest game versions? Or is it because of some mods, that alter Pixels/Voxels? It happened even with a newly created character (saved after playing the intro mission - escaping Earth), so with minimum cash. The latest public released version of Starcheat (0.27 for Glad Giraffe) is working kinda well (some features are disabled, like both hotbars, tech menu and quests, but most of the other things work). I was hoping to use a Starcheat version, that actually supposrts game versions above 1.0 (latest Starbound is like 1.3 or something) to have all the features available.

**Comment by chrmoritz** [comment]
@Levianne This is likely caused by a Starbound 1.0 change in the save format. Unfortunately starcheat didn't keep up with developing after the 1.0 release, because it completely changed the safe format and nobody wanted to put the needed effort in this project anymore to make it fully work again.

Also the latest nightly build for 1.0 support is [e9aeb3c](https://ci.appveyor.com/project/wizzomafizzo/starcheat/build/master-b74/job/ve8yig7de3sqf89c/artifacts), which should have at least this [money issue](https://github.com/wizzomafizzo/starcheat/pull/288/files#diff-f9357e65db51fbf3baefb4ecc21d2a7dL535) fixed. But not saying that there won't be any other issues ...

**Comment by Levianne** [comment]
@chrmoritz I've downloaded that exact build, in my download manager it reads "starcheat-e9aeb3c-win64(1).zip" which means, I still have that same file in my DL folder and when I launched SC from there, it was just the same like with the latest public release (the one for Glad Giraffe Starbound).
Actually checking just now in the Help section it also reads "Starcheat v. 0.27.1 (Glad Giraffe)". It doesn't seem like the nightly build for Starbound 1.0 support. That "a00f400" seems more likely to be the one with 1.0 SB support, though I can't confirm it, I won't get into the Help section until I pick a character to edit, and once I do, it crashes. The "Glad Giraffe" version lists also other characters (like a Munari, a Slime, one from the WhoBound mod, a Yautja and co.), while this "Nightly" does show only the two vanilla characters (both Floran, one is my main character, the other was created for testing after getting this error from selecting the main one). I guess, that being it a nightly build, it doesn't really support mods, or it somehow excludes them on purpose. That's the main difference I see in those two versions, the 0.27.1 seems to have less issues with mods, but an overall issue with functionality with some parts (Tech, Quests, the 2 Hotbars) unsupported, because they weren't implemented yet at that time, or something.

And yes, the 0.27.1 Starcheat works, as I mentioned before, but it doesn't work fully. Some features are "unsupported". That's, why I wanted to try the latest working (even non-public) version, to get the best out of it. (and because I'm a curious person :D) I'm using svegame editors in most games, that have them, but mostly not for cheating (despite it's called StrarCHEAT here), there's also the "Item spawn pack" mod, or what's it called for that purpose, but it won't allow me to alter the character's appearance.

**Comment by chrmoritz** [comment]
e9aeb3c is the latest nightly, even if it says something different in its about. That's why it is able to open your safes and as I said not all functionality is implemented for 1.0 yet (and it will probably never happen).

**Comment by Levianne** [comment]
Oh I see. That's unfortunate. So to have all the features I'd have to downgrade to Glad Giraffe, right? Just asking, because I'm fine with 1.3.3 and I don't really need all that extra stuff, that's greyed out in Starcheat either.

**Comment by chrmoritz** [comment]
Yeah, Glad Giraffe was the last Starbound version which was fully supported by starcheat.
