### ISSUE TITLE
Oops starcheat crashed

### ISSUE THREAD

**Issue by Nin10dope64** [wizzomafizzo/starcheat#356]
## Issue details:
*Please try to fill out as many fields as you can below (by replacing the text between the two *).*

* starcheat version: 0.27.1
* starbound version and branch (stable / unstable / nightly): 1.3.3 Spacefarer Stable
* the error message your a getting if any: Oops, starcheat has crashed
```
Insert error message from the details field of the error dialog here

Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 154, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 127, in find_assets
  File "build\assets\core.py", line 156, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

```
https://gist.github.com/Nin10dope64/e007feb046d3388223a0e728f1c44f42#file-starcheat-log

**Comment by chrmoritz** [comment]
starcheat 0.27.1 does only support the Starbound version `Glad Giraffe` (pre 1.0).
To get a partially working starcheat version with support for post 1.0 Starbound you could try the latest nightly from: https://ci.appveyor.com/project/wizzomafizzo/starcheat/build/master-b74/job/ve8yig7de3sqf89c/artifacts
