### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by WUTcappy** [wizzomafizzo/starcheat#365]
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 179, in __init__
  File "build\gui\mainwindow.py", line 546, in open_file
  File "build\gui\openplayer.py", line 161, in show
  File "build\gui\utils.py", line 197, in new_setup_dialog
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 140, in find_assets
  File "build\assets\core.py", line 148, in scan_modpak
  File "build\assets\sb_asset.py", line 47, in create_file_index
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 72: invalid start byte

**Comment by gen3vra** [comment]
this project is dead, try here https://github.com/gen3vra/starcheat-patched-bin
